### ISSUE TITLE
Too many inventory slots: slotId: 45 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#1016]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/ccbec9dd92e3024549ad37372ea73f7e932924d33c155fb4e30416bb4cacfb4a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord (with NuVotifier)

### How does this error happen? login? Using an item? 
Not sure.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[18:37:33 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 45 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[18:37:33 WARN]: java.lang.reflect.InvocationTargetException
[18:37:33 WARN]:        at sun.reflect.GeneratedMethodAccessor515.invoke(Unknown Source)
[18:37:33 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:37:33 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[18:37:33 WARN]:        at us.myles.ViaVersion.bukkit.providers.BukkitInventoryQuickMoveProvider.sendPacketToServer(BukkitInventoryQuickMoveProvider.java:142)
[18:37:33 WARN]:        at us.myles.ViaVersion.bukkit.tasks.protocol1_12to1_11_1.BukkitInventoryUpdateTask.run(BukkitInventoryUpdateTask.java:42)
[18:37:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:67)
[18:37:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:364)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:376)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:629)
[18:37:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:37:33 WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
[18:37:33 WARN]:        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[18:37:33 WARN]:        at java.util.ArrayList.get(ArrayList.java:433)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.Container.getSlot(Container.java:109)
[18:37:33 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1516)
[18:37:33 WARN]:        ... 12 more
```

**Comment by MylesIsCool** [comment]
Definitely seems like a weird one, does this happen to you personally? It obviously happens with some sort of inventory event but it's determining whether this happens on a vanilla client.

**Comment by MylesIsCool** [comment]
Going to close this as nobody else has this issue, I suspect it's down to either:

- Some weird plugin interface
- A hack client

If we're able to replicate it we'll happily look into further

**Comment by Brottweiler** [comment]
This happens for me with ViaVersion on a 1.8 server. I get these errors when I try to either take things out or into a chest, or crafting, and i close my inventory very quickly after doing so. There's a delay. I have to take the item out, or craft something, then wait a second before I close my inventory. Otherwise I get a ghost item.

Video showcasing it here https://streamable.com/fai5d

log after the video
```java
[14:10:26 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 43 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:10:29 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 45 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:10:31 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 51 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:10:33 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 51 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:10:34 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 49 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:10:45 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 89 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:11:34 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 50 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:11:36 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 50 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
[14:11:37 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 50 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING
```
