### ISSUE TITLE
Error in bungeecord console (with ViaVersion in spigot)

### ISSUE THREAD

**Issue by didjee2** [MylesIsCool/ViaVersion#1019]
### What is the output link of /viaversion dump? 
I am using a default viaversion config.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, last version

### How does this error happen? login? Using an item? 
It's an error that occurs in the bungeecord console, but ViaVersion is in (Paper)Spigot (together with ViaBackwards & ViaRewind)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```code
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
4100
at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
I get a similar error with packet 0d00

**Comment by MylesIsCool** [comment]
What is the output link of /viaversion dump?


Please fill in all the fields.

**Comment by didjee2** [comment]
Lobby 1:
https://dump.viaversion.com/91c2b5ce8bdac702d044614f11308297c4cf2536b44dd1485bf6942a7a06d686

Lobby 2:
https://dump.viaversion.com/9f43dda0d0076caf0c45df106c8ee074181fb073589a6abe48987c1c428bb7d5

(Errors occur with both of those servers, when people login into those servers, the error pops up in the bungee console)

**Comment by MylesIsCool** [comment]
Can you provide BungeeCord plugins too?

**Comment by didjee2** [comment]
We are busy converting our Bungeecords, the errors occur in both our BungeeCord servers:
(same errors in both servers)

Bungee 1: https://gyazo.com/6fe75a3b80f0a30557e10fcc05a0b554
Bungee 2: https://gyazo.com/9808a21bb0871ddd8f33874f1c6fe8df

CMS / CentrixCore are basically HubBalancers, a simple staff chat and some utilities (custom made plugins, in Spigot CentrixCore does much more)

BungeeUtilisals is a plugin also available on Spigot, however the newly recoded version is now only available at https://git.dbsoftwares.eu/DBSoftwares/BungeeUtilisals/src/development/
(There is one related thing with packets in this plugin, BossBar packets, but I have it disabled at the moment)

**Comment by MylesIsCool** [comment]
I'm going to close this issue, the main issue is we can't replicate it. If you're able to provide plugins where we can we can look into this and get it sorted, otherwise, it's bungee complaining about bad packets. Which might be down to us (though we're not seeing this case anywhere else though it could be rare) or could be a somehow down to a Bungee plugin/client issue.
