### ISSUE TITLE
[ViaVersion] Task #10292 for ViaVersion v1.5.1-SNAPSHOT generated an exception

### ISSUE THREAD

**Issue by sergservis** [MylesIsCool/ViaVersion#1031]
On the version ViaVersion v1.5.1 from the ViaRevind and ViaBackwards players can not enter from version 1.8. Server Core 1.12.2

[10:06:28 WARN]: [ViaVersion] Task #10292 for ViaVersion v1.5.1-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.data.UserConnection.getChannel()Lio/netty/channel/socket/SocketChannel;
        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown$1.run(Cooldown.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[spigot.jar:git-Paper-1547]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1547]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1547]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1547]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1547]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1547]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by creeper123123321** [comment]
Update viarewind and wait for #1030

**Comment by sergservis** [comment]
The problem did not disappear

**Comment by MylesIsCool** [comment]
You need latest dev build of ViaRewind https://ci.viaversion.com/view/ViaRewind/
