### ISSUE TITLE
Unable to read type String Array, found VarInt

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#1052]
### What is the output link of /viaversion dump? 
It seems like viaversion dump is also not working at the moment (cloudflare timeout), the issue is present with latest ViaVersion from CI server.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
On join.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[10:16:49 WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: String Array, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$14 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$14$1 (Anonymous), Data: [Pair{Type|String, viaversion}, Pair{Type|Byte, 0}, Pair{Type|String, {"extra":["viaversion"],"text":""}}, Pair{Type|Byte, 0}, Pair{Type|String, }, Pair{Type|String, never}, Pair{Type|VarInt, 21}, Pair{Type|String, {"extra":[""],"text":""}}, Pair{Type|String, {"extra":[{"color":"white","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":""}],"text":""}}], Packet ID: 71}
Actual Error:
[10:16:49 WARN]: Caused by: java.io.IOException: Unable to read type String Array, found VarInt
[10:16:49 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:158)
[10:16:49 WARN]:        at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$14$1.handle(Protocol1_13To1_12_2.java:452)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:149)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:425)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:333)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
[10:16:49 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.storage.EntityTracker.sendTeamPacket(EntityTracker.java:268)
[10:16:49 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$7$1.handle(WorldPackets.java:220)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:149)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:425)
[10:16:49 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[10:16:49 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[10:16:49 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[10:16:49 WARN]:        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
[10:16:49 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:49 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[10:16:49 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[10:16:49 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490)
[10:16:49 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262)
[10:16:49 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:16:49 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[10:16:49 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[10:16:49 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[10:16:49 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[10:16:49 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[10:16:49 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.lambda$0(NetworkManager.java:196)
[10:16:49 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345)
[10:16:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[10:16:49 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[10:16:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:16:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by L4BORG** [comment]
```ViaVersion version 1.5.3-SNAPSHOT
```
