### ISSUE TITLE
1.7 players get kicked

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1125]
Kick reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
I don't know if its the same but it heres log from the console: 

> [13:01:19] [Server thread/INFO]: x lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:01:19] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:01:19] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	... 18 more
[13:01:19] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.NoSuchMethodError: us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8.<init>(IIZI[Lus/myles/ViaVersion/api/minecraft/chunks/ChunkSection;[BLjava/util/List;)V
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.read(Chunk1_8Type.java:82)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.read(Chunk1_8Type.java:17)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.type.PartialType.read(PartialType.java:19)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:145)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1$1.handle(WorldPackets.java:42)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:149)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:143)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:425)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:01:19] [Netty Epoll Server IO #3/WARN]: 	... 22 more
[13:01:19] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[13:01:19] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException

**Comment by MylesIsCool** [comment]
Update your Via plugins

**Comment by DanielAlves123** [comment]
@MylesIsCool tested on latest versions.
