### ISSUE TITLE
Startup error 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [MylesIsCool/ViaVersion#1129]
1. Server start
2. i get error on server start

When i Start server i get this error:
```
 [ViaVersion] Task #28 for ViaVersion v2.0.0-SNAPSHOT generated an exception
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
at us.myles.ViaVersion.util.Config.getString(Config.java:151) ~[?:?]
at us.myles.ViaVersion.bukkit.platform.BukkitViaConfig.getBlockConnectionMethod(BukkitViaConfig.java:230) ~[?:?]
at us.myles.ViaVersion.bukkit.platform.BukkitViaLoader.load(BukkitViaLoader.java:97) ~[?:?]
at us.myles.ViaVersion.ViaManager.onServerLoaded(ViaManager.java:90) ~[?:?]
at us.myles.ViaVersion.ViaManager$1.run(ViaManager.java:65) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

No screenShots

https://dump.viaversion.com/96074cdb9882118c25c0cac28b8c1e607243632e50aaff8b7c194ef5b4eea5d3

BungeeCord

**Comment by Gerrygames** [comment]
Your config is faulty. „blockconnection-method“ has to be a string, not a boolean.
