### ISSUE TITLE
Could not find type id 12 isObject=false

### ISSUE THREAD

**Issue by andris155** [MylesIsCool/ViaVersion#1132]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
```
[14:13:44] [Netty Epoll Server IO #2/ERROR]: [ViaVersion] Could not find type id 12 isObject=false
[14:13:44] [Netty Epoll Server IO #2/ERROR]: [ViaVersion] Could not find type id 12 isObject=false
[14:13:44] [Netty Epoll Server IO #2/ERROR]: [ViaVersion] Could not find type id 12 isObject=false
[14:13:44] [Netty Epoll Server IO #2/ERROR]: [ViaVersion] Could not find type id 12 isObject=false
```

**How can we reproduce it?**
I don't know. Find this error on console.

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
Not work with Java 11
```
[15:06:08] [Craft Scheduler Thread - 347/INFO]: Failed to dump, please check the console for more information
[15:06:08] [Craft Scheduler Thread - 347/WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
javax.net.ssl.SSLException: Received fatal alert: record_overflow
	at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
	at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-492]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:06:08] [Craft Scheduler Thread - 347/WARN]: [ViaVersion] Failed to capture further info
javax.net.ssl.SSLException: Received fatal alert: record_overflow
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
	at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-492]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
	at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
	at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:75) ~[?:?]
	... 6 more
```

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
`This server is running Paper version git-Paper-492 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

`Waterfall build 245`

`Plugins (99): 2048*, AdditionsAPI, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, Battleship*, BestViewDistance, ChangeSkin, ChatControl, ChestCommands, ChestShop, Citizens, CitizensCMD, CombatLogX, CommandHook, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CrateReloaded, CrazyAuctions, CreativeNbtControl, Duels, EnderContainers, EntityDetection*, EpicHeads, Essentials, EssentialsChat*, EssentialsGeoIP*, EssentialsSpawn*, EventekGUI, EventRendszer, GameBox*, GemCrush*, GriefPrevention, GriefPreventionFlags, JukeBox, Kezdes, Kredites, LockettePro, LogicPuzzles*, Lottery, LuckPerms*, mcMMO, MineMarket-Universal, MineMarketAPI, Minesweeper*, MobArena, MobFarmManager, MobHeads, MP-GameBundle*, Multiverse-Core*, Multiverse-NetherPortals*, MyCommand*, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, Paintball, PickupSpawners, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan*, PomaAdditions, ProtocolLib*, RandomTeleport, RedstoneClockDetector*, RestrictedCreative, Ridables, Shopkeepers, SignEdit*, Stats, SuperLuckyBlock-Pro, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaBackwards*, ViaVersion*, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WhacAMole*, WorldBorderPearlBlock*, WorldEdit, WorldGuard, WorldGuardExtraFlags*, WorldGuardPomaFlags, YouTubeBridge`

`ViaVersion v2.0.0-SNAPSHOT`
`ViaBackwards v2.4.0-SNAPSHOT`

**Comment by MylesIsCool** [comment]
Hi,
ViaBackwards is not fully updated to 1.13.2 - Use ProtocolSupport dev builds :) 

In regards to the SSL error, It might just be a hiccup somewhere or something to do with a server outage? (Unsure honestly)
