### ISSUE TITLE
ViaVersion on Travertine

### ISSUE THREAD

**Issue by AntoLuMeju99** [MylesIsCool/ViaVersion#1168]
[22:06:02 WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0xa257a9ac, L:/185.25.204.218:25565 ! R:/95.251.238.110:59035]
java.util.NoSuchElementException: packet-encoder
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at us.myles.ViaVersion.bungee.handlers.BungeeChannelInitializer.initChannel(BungeeChannelInitializer.java:37) ~[?:?]
at us.myles.ViaVersion.bungee.handlers.BungeeChannelInitializer.initChannel(BungeeChannelInitializer.java:11) ~[?:?]
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:427) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:7b74a5c:78]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by Leymooo** [comment]
#716

**Comment by MylesIsCool** [comment]
Should be fixed in latest build from ci.viaversion.com

**Comment by AntoLuMeju99** [comment]
It's stable? When it will be uploaded on SpigotMc?
