### ISSUE TITLE
An exception was thrown by a user handler's exceptionCaught() method while handling the following exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#142]
### What version of ViaVersion are you using? Type /ver viaversion
```
viaversion
[01:05:02 INFO]: ViaVersion 0.5.2
[01:05:02 INFO]: Commands:
[01:05:02 INFO]: /viaversion list - Shows lists of all 1.9 clients and 1.8 clients.
```

### What version of Spigot are you using? Type /ver
```
ver
[01:05:35 INFO]: This server is running CraftBukkit version git-PaperSpigot-"5c510af" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### What plugins are you using? Type /plugins
```
pl
[01:06:00 INFO]: Plugins (19): AsyncWorldEditInjector, ServerManager, NoCheatPlus, AutoSaveWorld, WorldEdit, AsyncWorldEdit, OpenInv, LogBlock, ServerSelector, Buycraft, ViaVersion, WorldBorder, HolographicDisplays, Vault, WorldGuard, BungeePortals, Essentials, EchoPet, TrailGUI
```

### How does this error happen? login? Using an item? 
It seem random... (with 25 players online on lobby server)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[01:00:37 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at org.spacehq.mc.protocol.util.NetUtil.readOldChunkData(NetUtil.java:108) ~[?:?]
        at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:639) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:62) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
        ... 11 more
```

**Comment by MylesIsCool** [comment]
Fixed in future versions
