### ISSUE TITLE
/reload issues

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#286]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.0

### What version of Spigot are you using? Type /ver
CraftBukkit version git-TacoSpigot-"e026d35" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### What plugins are you using? Type /plugins
AsyncWorldEditInjector, ServerManager, PlayerWarps, AutoSaveWorld, GuiRedeemMCMMO, AsyncWorldEdit, GlobalMarket, mcMMO, ViaVersion, Vault, MassiveCore, WorldEdit, Essentials, SkyWarsReloaded, LogBlock, Auctions, CrateReloaded, SilkSpawners, ProtocolLib, WorldGuard, AuctionHousePlus, NoCheatPlus, KitAdder, Factions, NoCheatEnforcer, EchoPet, FactionsPlus, PlayerVaults, EssentialsSpawn, GriefPrevention, CombatTagPlus, ChestShop, RPG, KingOfTheHill, UserManager, GriefPreventionFlags

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:aaddc9f:1135 by md_5
Plugins: ServerListPlus, SkinsRestorer, NuVotifier

### How does this error happen? login? Using an item? 
on /reload

### Is there an error in the console? Use pastebin.com. Is there a kick message?
On reload
```
[22:23:03] [Netty Epoll Server IO #2/WARN]: Failed to initialize a channel. Closing: [id: 0x1510aeea, /127.0.0.1:52647 => /127.0.0.1:40000]
java.lang.ClassCastException: us.myles.ViaVersion.ViaVersionPlugin cannot be cast to us.myles.ViaVersion.ViaVersionPlugin
	at us.myles.ViaVersion.protocols.base.BaseProtocol.registerListeners(BaseProtocol.java:151) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:23) ~[?:?]
	at us.myles.ViaVersion.protocols.base.BaseProtocol.<init>(BaseProtocol.java:26) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.registerPackets(ProtocolPipeline.java:32) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:22) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.<init>(ProtocolPipeline.java:24) ~[?:?]
	at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:32) ~[?:?]
	at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:13) ~[?:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [patched.jar:git-TacoSpigot-"e026d35"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-TacoSpigot-"e026d35"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

and after that I'd see ..
```
[22:23:08 WARN]: Failed to initialize a channel. Closing: [id: 0xf0cc532b, /127.0.0.1:52681 => /127.0.0.1:40000]
java.lang.ClassCastException: us.myles.ViaVersion.ViaVersionPlugin cannot be cast to us.myles.ViaVersion.ViaVersionPlugin
        at us.myles.ViaVersion.protocols.base.BaseProtocol.registerListeners(BaseProtocol.java:151) ~[?:?]
        at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:23) ~[?:?]
        at us.myles.ViaVersion.protocols.base.BaseProtocol.<init>(BaseProtocol.java:26) ~[?:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.registerPackets(ProtocolPipeline.java:32) ~[?:?]
        at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:22) ~[?:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.<init>(ProtocolPipeline.java:24) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:32) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:13) ~[?:?]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [patched.jar:git-TacoSpigot-"e026d35"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-TacoSpigot-"e026d35"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

spamming...

**Comment by HugoDaBosss** [comment]
We don't support reloads.

**Comment by MylesIsCool** [comment]
Reloads are not supported, never have been. We suggest using a plugin manager like plugman to load and unload plugins.
