### ISSUE TITLE
No Such Field Exception: childHandler

### ISSUE THREAD

**Issue by HeroCC** [MylesIsCool/ViaVersion#3]
When I install this plugin, I get this error: 

> [15:25:33 INFO]: [ViaVersion] Enabling ViaVersion v0.2
[15:25:33 INFO]: ViaVersion enabled, injecting. (Allows 1.8 to be accessed via 1.9)
[15:25:33 INFO]: Unable to inject handlers, are you on 1.8?
[15:25:33 WARN]: java.lang.NoSuchFieldException: childHandler
[15:25:33 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[15:25:33 WARN]:        at us.myles.ViaVersion.ReflectionUtil.get(ReflectionUtil.java:31)
[15:25:33 WARN]:        at us.myles.ViaVersion.Core.injectPacketHandler(Core.java:45)
[15:25:33 WARN]:        at us.myles.ViaVersion.Core.onEnable(Core.java:25)
[15:25:33 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:25:33 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:25:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:25:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:25:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:25:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[15:25:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[15:25:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[15:25:33 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[15:25:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:25:33 WARN]:        at java.lang.Thread.run(Thread.java:745)

Version: `This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
`, the latest as of now

Any help is appreciated!

**Comment by Yive** [comment]
Not compatible with ProtocolLib.

**Comment by HeroCC** [comment]
Is support planned / possible?
