### ISSUE TITLE
/viaver list - Error on PaperSpigot

### ISSUE THREAD

**Issue by ViaList** [MylesIsCool/ViaVersion#314]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.3
### What version of Spigot are you using? Type /ver
PaperSpigot 1.8 Final Build
### What plugins are you using? Type /plugins
Not leaking this.
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, just paperspigot
### How does this error happen? login? Using an item? 
Everytime I use /viaver list
### Is there an error in the console? Use pastebin.com. Is there a kick message?
org.bukkit.command.CommandException: Unhandled exception executing command 'viaver' in plugin ViaVersion v0.7.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils£0.7.run(SourceFile:13) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.UnsupportedOperationException
at java.util.AbstractCollection.add(AbstractCollection.java:262) ~[?:1.8.0_77]
at us.myles.ViaVersion.commands.defaultsubs.ListSubCmd.execute(ListSubCmd.java:34) ~[?:?]
at us.myles.ViaVersion.commands.ViaCommandHandler.onCommand(ViaCommandHandler.java:67) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]

**Comment by ViaList** [comment]
"An internal error occurred while attempting to perform this command"

It worked on ViaVersion 0.7.2

**Comment by HugoDaBosss** [comment]
Not fixed, but should be fixed now thanks to @Matsv #319
