### ISSUE TITLE
Plugin attempted to register BaseProtocol while not enabled

### ISSUE THREAD

**Issue by MedicOP** [MylesIsCool/ViaVersion#323]
ViaVersion loads before ProtocolLib. When ProtocolLib loads, it generates this error. The same error seems to happen for PEX and NCP.

ViaVersion actually "enables" after these other plugins have already loaded, not sure if that is a problem. 

### What version of ViaVersion are you using? Type /ver viaversion
0.7.4-SNAPSHOT

### What version of Spigot are you using? Type /ver
git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
ViaVersion, WorldEdit,, ProtocolLib, NoCheatPlus, PermissionsEx, DisguiseCraft, HolographicDisplays, WorldGuard, ChatManager, EchoPet

### Are you using any additional software like BungeeCord? If so, what software and version? 
BungeeCord, latest version released on 31 March

### How does this error happen? login? Using an item?
It happens during server startup and also shutdown

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```java
[20:54:41] [Netty Epoll Server IO #1/WARN]: Failed to initialize a channel. Closing: [id: 0xaefcff68, /172.16.0.2:59112 => /172.16.0.2:1332]
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register us.myles.ViaVersion.protocols.base.BaseProtocol$4@43d0a272 while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) ~[craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at us.myles.ViaVersion.protocols.base.BaseProtocol.registerListeners(BaseProtocol.java:153) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:23) ~[?:?]
	at us.myles.ViaVersion.protocols.base.BaseProtocol.<init>(BaseProtocol.java:26) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.registerPackets(ProtocolPipeline.java:32) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:22) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.<init>(ProtocolPipeline.java:24) ~[?:?]
	at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:32) ~[?:?]
	at us.myles.ViaVersion.handlers.ViaVersionInitializer.initChannel(ViaVersionInitializer.java:13) ~[?:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [craftbukkit.jar:git-Spigot-76236cb-62a2169]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by MylesIsCool** [comment]
Fixed in next versiom
