### ISSUE TITLE
error on startup using latest version

### ISSUE THREAD

**Issue by Twi5TeD** [MylesIsCool/ViaVersion#324]
### What version of ViaVersion are you using? Type /ver viaversion
[23:56:01 INFO]: ViaVersion version 0.7.3
[23:56:01 INFO]: Author: _MylesC

### What version of Spigot are you using? Type /ver
 This server is running CraftBukkit version git-TacoSpigot-"c80c1e5" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[23:56:19 INFO]: Checking version, please wait...
[23:56:19 INFO]: You are 144 commit(s) behind

### What plugins are you using? Type /plugins
[23:56:34 INFO]: Plugins (75): GiveAll, PlaceholderAPI, VoidWorld, DeluxeCommands, PlugMan, BanManager, ChatReaction, AlwaysDay, UniMuteChat, DeluxeTags, EditableSign, UniSpawn, EpicWorldGenerator, Simple-AutoSave, ViaVersion, UniABC, UniversalMcCore, PotionStacker, ChatReactionPlus, VoteRemind, ClearLag, StopCrafting, BuycraftX, Votifier, NameMyItem, ProtocolLib, UniClearChat, weeTrade, eZProtector, FastAsyncWorldEdit, CosmicChest, DeluxeMenus, FeatherBoard, Lottery, ActionAnnouncer, Vault, Lores, VoteParty, AAC, AuctionHouse, UniBlockBreaker, EZPrestige, EZRanksPro, OneTimeItem, WorldEdit, Essentials, AnimatedNames, PermissionTimer, CrateReloaded, PowerfulPerms, PlotSquared, WorldGuard, ServerSigns, EssentialsSpawn, TitleManager, Multiverse-Core, AsyncPVP, PlotMines, GAListener, CombatTagPlus, ChestShop, TokenEnchant, HolographicDisplays, GangsPlus, PrisonMines, AutoSell, MineCrates, MineBows, InvFull, EZBlocks, HolographicExtension, LeaderHeads, ToolUpgrade, DeluxeChat, ItemHover

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/1eKJFxx7
on startup this just spams console
worked fine before i updated to latest version not sure what caused it though

**Comment by Twi5TeD** [comment]
also 
[23:59:38] [Server thread/INFO]: F64_Rx issued server command: /viaversion list
[23:59:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'viaversion' in plugin ViaVersion v0.7.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c80c1e5"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractCollection.add(AbstractCollection.java:262) ~[?:1.8.0_77]
	at us.myles.ViaVersion.commands.defaultsubs.ListSubCmd.execute(ListSubCmd.java:34) ~[?:?]
	at us.myles.ViaVersion.commands.ViaCommandHandler.onCommand(ViaCommandHandler.java:67) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
	... 15 more

**Comment by MedicOP** [comment]
Startup error was fixed in c7c6ee9
Command error was fixed in 1fa7211

**Comment by Twi5TeD** [comment]
has it been updated on spigot or not yet?

**Comment by MylesIsCool** [comment]
It will be updated today you can use a unofficial build like: http://build.fillecraft.com:8080/job/ViaVersion/lastBuild/us.myles$viaversion/

If you want it early.

**Comment by Twi5TeD** [comment]
yh found it before thanks anyway :)
