### ISSUE TITLE
Could not find valid metadata

### ISSUE THREAD

**Issue by MedicOP** [MylesIsCool/ViaVersion#343]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4

### What version of Spigot are you using? Type /ver
git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
EchoPet, DisguiseCraft, ProtocolLib, NoCheatPlus

### Are you using any additional software like BungeeCord? If so, what software and version?
BungeeCord

### How does this error happen? login? Using an item?
No idea to be honest, could be EchoPet or DisguiseCraft? 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```java
[10:29:50 INFO]: INCLUDE THIS IN YOUR ERROR LOG!
[10:29:50 INFO]: An error occurred with entity meta data for CREEPER OldID: 12
[10:29:50 WARN]: java.lang.Exception: Could not find valid metadata
[10:29:50 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.metadata.MetadataRewriter.transform(MetadataRewriter.java:140)
[10:29:50 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.SpawnPackets$5$3.handle(SpawnPackets.java:213)
[10:29:50 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[10:29:50 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:93)
[10:29:50 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:137)
[10:29:50 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:74)
[10:29:50 WARN]:        at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:54)
[10:29:50 WARN]:        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[10:29:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:29:50 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[10:29:50 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[10:29:50 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490)
[10:29:50 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262)
[10:29:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:29:50 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[10:29:50 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[10:29:50 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[10:29:50 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[10:29:50 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[10:29:50 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[10:29:50 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345)
[10:29:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[10:29:50 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[10:29:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:29:50 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Matsv** [comment]
Do you use the 1.8 versions from Echopet and DisguiseCraft?

**Comment by MedicOP** [comment]
Yes

**Comment by ridalarry** [comment]
@MedicOP are you using AAC or AntiAura?

**Comment by MedicOP** [comment]
No, but I am using NoCheatPlus

**Comment by MedicOP** [comment]
More info: The error message happens for different mobs, not just Creepers. It happens for squids, snowmen, etc. Still not sure what causes it

One thing though, no matter which mob is stated in the error, the OldId is always 12. Might be of interest?

```java
[21:22:45] [Netty Epoll Server IO #2/INFO]: INCLUDE THIS IN YOUR ERROR LOG!
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:74)
[21:22:45] [Netty Epoll Server IO #2/INFO]: An error occurred with entity meta data for SNOWMAN OldID: 12
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:54)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:22:45] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:22:45] [Netty Epoll Server IO #1/WARN]: java.lang.Exception: Could not find valid metadata
[21:22:45] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.metadata.MetadataRewriter.transform(MetadataRewriter.java:139)
[21:22:45] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.SpawnPackets$5$3.handle(SpawnPackets.java:213)
[21:22:45] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
```

**Comment by MedicOP** [comment]
I've identified the problem to be caused by DisguiseCraft. When you disguise as for example a Creeper, immediately the error is spammed a few times in the console.

The disguise works fine and other people can see it, but the error is spammed.

**Comment by Matsv** [comment]
@MedicOP you can change the config option suppress-metadata-errors, that will stop the error from displaying in console

**Comment by MedicOP** [comment]
Okay, is the error itself an issue or does it not affect performance?

**Comment by Matsv** [comment]
Well it's an issue from one of you plugins (probably libsdiguises) that's sending non-existing metadata, viaversion is removing those non-existing fields and notifying the server about it by sending error messages, it could ofcourse affect performance if the console get spammed every tick if you are sending invalid metadata. That's why the config option is there :smile:

**Comment by MedicOP** [comment]
Okay thank you
