### ISSUE TITLE
DecoderException : java.lang.IndexOutOfBoundsException @ io.netty.handler.codec.MessageToMessageDecoder:99

### ISSUE THREAD

**Issue by Paulomart** [MylesIsCool/ViaVersion#39]
Having a problem with the last commit: 318db73f3c7b48eaa5421cd4da460950fc5388a7

With our own patch: Mystalion/ViaVersion this is not happining.

**Comment by Paulomart** [comment]
Also not sure why this happing the server this is on tih pretty blank.

**Comment by MylesIsCool** [comment]
Any chance I can get the full stack trace?

**Comment by Paulomart** [comment]
On server or client?

**Comment by MylesIsCool** [comment]
server please

**Comment by Paulomart** [comment]
Nothing:
```
[16:43:22 INFO]: UUID of player Paulomart is c4ee8311-4150-481b-849f-8a8a263421b0
[16:43:22 INFO]: Paulomart[/79.228.204.60:59525] logged in with entity id 0 at ([limbo]-27.5, 246.0, -25.5)
[16:43:22 INFO]: Paulomart lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[16:43:22 INFO]: Paulomart left the game.
```

**Comment by Paulomart** [comment]
Would bet it is somethink with a team packet, its just a world on the server, not entity (see eID of me)

**Comment by Paulomart** [comment]
GITHUB MOBILE ARRR

**Comment by L4BORG** [comment]
I'm getting this too...

```
DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 862, cap: 4096)) @ io.netty.handler.codec.MessageToMessageDecoder:99
```

with v0.4.0

**Comment by MylesIsCool** [comment]
Enable debug in server properties and then try connecting to see if you can get a full error. Thanks!

**Comment by L4BORG** [comment]
1.8.9 client connecting to latest 1.8.9 server with viaversion 0.4.0 would get disconnected, error in console: 

```
[17:16:17 INFO]: Player[/127.0.0.1:60030] logged in with entity id 797 at ([world]1.5339554858729212, 62.0, 18.35194446824346)
[17:16:17 WARN]: java.io.IOException: Error while write(...): Broken pipe
[17:16:17 WARN]:        at io.netty.channel.epoll.Native.writeAddress(Native Method)
[17:16:17 WARN]:        at io.netty.channel.epoll.EpollSocketChannel.writeBytes(EpollSocketChannel.java:125)
[17:16:17 WARN]:        at io.netty.channel.epoll.EpollSocketChannel.doWriteSingle(EpollSocketChannel.java:337)
[17:16:17 WARN]:        at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:325)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707)
[17:16:17 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:240)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:676)
[17:16:17 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1059)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[17:16:17 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[17:16:17 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[17:16:17 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:718)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[17:16:17 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[17:16:17 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[17:16:17 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[17:16:17 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[17:16:17 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[17:16:17 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[17:16:17 WARN]:        at java.lang.Thread.run(Thread.java:745)
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 WARN]: java.nio.channels.ClosedChannelException
[17:16:17 INFO]: Player lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
```

that's with debug=true

**Comment by MylesIsCool** [comment]
What plugins are you using? Does this only occur when connecting with 1.8? 

Thanks!

**Comment by MylesIsCool** [comment]
Fixed in version 0.4.1.

**Comment by craftrise** [comment]
@MylesIsCool , i have same error: (with latest viaversion)

https://hastebin.com/sofucijozu.lua

**Comment by MylesIsCool** [comment]
@craftrise Remove plugins and test
