### ISSUE TITLE
Throwable after restart

### ISSUE THREAD

**Issue by EvilOlaf** [MylesIsCool/ViaVersion#415]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.2

### What version of Spigot are you using? Type /ver
Spigot 1.8.8

### What plugins are you using? Type /plugins
If important let me know

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No

### How does this error happen? login? Using an item? 
Not reproducable

### Is there an error in the console? Use pastebin.com. Is there a kick message?

After restart noticed this exception in the log files:
```
[20:06:20] [Netty Epoll Server IO #1/ERROR]: Chunk (-69, -240) stored at  (-219, 361) in world 'Survival'
[20:06:20] [Netty Epoll Server IO #1/ERROR]: net.minecraft.server.v1_8_R3.Chunk
[20:06:20] [Netty Epoll Server IO #1/WARN]: java.lang.Throwable
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:204)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.World.getChunkAt(World.java:355)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.World.getChunkAtWorldCoords(World.java:351)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.World.getType(World.java:784)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at org.spigotmc.AntiXray.hasTransparentBlockAdjacent(AntiXray.java:216)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at org.spigotmc.AntiXray.hasTransparentBlockAdjacent(AntiXray.java:220)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at org.spigotmc.AntiXray.obfuscate(AntiXray.java:141)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunkBulk.b(PacketPlayOutMapChunkBulk.java:73)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.PacketEncoder.a(SourceFile:46)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.PacketEncoder.encode(SourceFile:16)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.util.PipelineUtil.callEncode(PipelineUtil.java:47)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:39)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:06:20] [Netty Epoll Server IO #1/WARN]:     at java.lang.Thread.run(Thread.java:745)
```

**Comment by Matsv** [comment]
Could you update to the latest version and see if it still happens?

**Comment by EvilOlaf** [comment]
Will do.

**Comment by EvilOlaf** [comment]
Sorry, forgot to mention. But this was a restart after a crash. Might be important to know.
```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/2/16 8:05 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)

-- Block entity being ticked --
Details:
        Name: Hopper // net.minecraft.server.v1_8_R3.TileEntityHopper
        Block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-188,3,83), Chunk: (at 4,0,3 in -12,5; contains blocks -192,0,80 to -177,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Actual block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)

-- Affected level --
Details:
        Level name: city
        All players: 7 total; [EntityPlayer['xxxx'/2742, l='city', x=-617.73, y=77.00, z=-535.91](xxxxat -617.7336402292409,77.0,-535.9079784152805), EntityPlayer['xxxxx'/9606, l='city', x=-191.06, y=67.11, z=113.11](xxxxxat -191.0617244263169,67.11163305637575,113.11096169466497), EntityPlayer['xxxxxx'/273257, l='city', x=-177.37, y=65.00, z=65.53](xxxxxxat -177.3746786558875,65.0,65.53051386633265), EntityPlayer['xxxxxxx'/613551, l='city', x=-798.66, y=65.00, z=-634.95](xxxxxxxat -798.6629990254614,65.0,-634.9505896569533), EntityPlayer['xxxxxxxx'/571470, l='city', x=-175.49, y=65.79, z=36.30](xxxxxxxxat -175.4884897008156,65.78502770378924,36.3029954280625), EntityPlayer['xxx'/161322, l='city', x=-663.04, y=65.00, z=-638.95](xxxat -663.0360883975217,65.0,-638.9532603604677), EntityPlayer['M0LLum'/7624, l='city', x=-669.57, y=61.00, z=-620.70](M0LLum at -669.5667242558745,61.0,-620.6999999880791)]
        Chunk stats: ServerChunkCache: 633 Drop: 0
        Level seed: -6483538616250838803
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: 0.00,66.00,0.00 - World: (0,66,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 858906755 game time, 859455514 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 91088 (now: false), thunder time: 78312 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:745)

```
For privacy reasons I edited the player names. I also stripped the threads that were dumped because they basically unformatted waste. Kind a pain in the butt to read. If interested anyways let me know.

**Comment by MylesIsCool** [comment]
Does this issue happen a lot, have you tested without Via? Seems odd as it's hopper related

**Comment by EvilOlaf** [comment]
There were a few crashes with hoppers as reason. However the crashes themselves are probably not related to viaversion. I set alternative hopper ticking back to false to see if it persists.

**Comment by EvilOlaf** [comment]
Yep, persists...

**Comment by MylesIsCool** [comment]
@EvilOlaf I'd suggest taking this up with spigot possibly. But you will be using an outdated version and would need to replicate in 1.10

**Comment by EvilOlaf** [comment]
The 1.8.8 build I use is the latest buildtools will generate in this branch. Also I am not up to updating to 1.9 or higher.

**Comment by TiTo-418** [comment]
@EvilOlaf Then upgrade to the latest version :P

**Comment by EvilOlaf** [comment]
As it seems like the throwable had/has no affect to gameplay and is probably not reproducible as well I will not take any further action here.
