### ISSUE TITLE
Splash Potions on Spigot 1.8.8 crashes 1.10 clients

### ISSUE THREAD

**Issue by joserobjr** [MylesIsCool/ViaVersion#425]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.9.0 
https://ci.viaversion.com/job/ViaVersion%201.10%20DEV/15/

### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (1): ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? 
No, pure Spigot with pure ViaVersion.

### How does this error happen? login? Using an item? 
Get any splash potion and trow it. Does not happens on spigot 1.9.4

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```java
Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Boolean
	at rw.ae(SourceFile:872)
	at aah.m(SourceFile:258)
	at aid.a(SourceFile:1520)
	at aid.g(SourceFile:1498)
	at aid.k(SourceFile:1388)
	at bcx.t(SourceFile:1652)
	at bcx.av(SourceFile:968)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at rw.ae(SourceFile:872)
	at aah.m(SourceFile:258)
	at aid.a(SourceFile:1520)
	at aid.g(SourceFile:1498)

-- Entity being ticked --
Details:
	Entity Type: ThrownPotion (aal)
	Entity ID: 155
	Entity Name: Poção
	Entity's Exact location: -34.70, 67.73, -0.81
	Entity's Block location: World: (-35,67,-1), Chunk: (at 13,4,15 in -3,-1; contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.02, 0.23, 0.40
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at aid.k(SourceFile:1388)
```

**Comment by Matsv** [comment]
Fixed https://github.com/MylesIsCool/ViaVersion/commit/f8ac54e237824eef92a2ac347de894832616442a
download the latest version from the buildserver

**Comment by joserobjr** [comment]
I see, the link's just gone lol I'm updating, thanks.
