### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(89) exceeds writerIndex(94): UnpooledHeapByteBuf(ridx: 10, widx: 94, cap: 128)

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#43]
```
[20:46:33 INFO]: throwing
[20:46:33 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(89) exceeds writerIndex(94): UnpooledHeapByteBuf(ridx: 10, widx: 94, cap: 128)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(89) exceeds writerIndex(94): UnpooledHeapByteBuf(ridx: 10, widx: 94, cap: 128)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at us.myles.ViaVersion.util.PacketUtil.readString(PacketUtil.java:95) ~[?:?]
        at us.myles.ViaVersion.transformers.IncomingTransformer.transform(IncomingTransformer.java:78) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaDecodeHandler.decode(ViaDecodeHandler.java:33) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        ... 18 more
[20:46:33 WARN]: java.lang.reflect.InvocationTargetException
[20:46:33 WARN]:        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[20:46:33 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:46:33 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[20:46:33 WARN]:        at us.myles.ViaVersion.util.PacketUtil.callDecode(PacketUtil.java:48)
[20:46:33 WARN]:        at us.myles.ViaVersion.handlers.ViaDecodeHandler.decode(ViaDecodeHandler.java:41)
[20:46:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[20:46:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:46:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:46:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:46:33 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:46:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:46:33 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[20:46:33 WARN]:        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[20:46:33 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[20:46:33 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[20:46:33 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:46:33 WARN]:        at java.lang.Thread.run(Thread.java:745)
[20:46:33 WARN]: Caused by: java.io.IOException: Packet 0/20 (PacketPlayInTabComplete) was larger than I expected, found 109 bytes extra whilst reading packet 20
[20:46:33 WARN]:        at net.minecraft.server.v1_8_R3.PacketDecoder.decode(SourceFile:42)
[20:46:33 WARN]:        ... 24 more
```

Using ViaVersion 0.4.3

**Comment by MylesIsCool** [comment]
Could possibly be PaperSpigot?

**Comment by L4BORG** [comment]
Yes! Is PaperSpigot not supported? :'(

**Comment by Paulomart** [comment]
Yes!

**Comment by MylesIsCool** [comment]
Closing, might be fixed. Could be paper spigot bug.
