### ISSUE TITLE
incoming packet not found 147455 state: PLAY

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#44]
```
[20:52:17 INFO]: incoming packet not found 147455 state: PLAY
[20:52:17 INFO]: throwing
[20:52:17 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Incoming Packet not found? 147455 State: PLAY Version: 107
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Incoming Packet not found? 147455 State: PLAY Version: 107
        at us.myles.ViaVersion.transformers.IncomingTransformer.transform(IncomingTransformer.java:27) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaDecodeHandler.decode(ViaDecodeHandler.java:33) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        ... 18 more
```

Using ViaVersion 0.4.3.

**Comment by L4BORG** [comment]
```
[20:55:31 INFO]: incoming packet not found 80 state: PLAY
[20:55:31 INFO]: throwing
[20:55:31 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Incoming Packet not found? 80 State: PLAY Version: 107
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Incoming Packet not found? 80 State: PLAY Version: 107
        at us.myles.ViaVersion.transformers.IncomingTransformer.transform(IncomingTransformer.java:27) ~[?:?]
        at us.myles.ViaVersion.handlers.ViaDecodeHandler.decode(ViaDecodeHandler.java:33) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[spigot-lobby3.jar:git-PaperSpigot-"5c510af"]
        ... 18 more
```

another one...

**Comment by MylesIsCool** [comment]
plugins?

**Comment by L4BORG** [comment]
```
AsyncWorldEditInjector, NoCheatPlus, AutoSaveWorld, WorldEdit, AsyncWorldEdit, OpenInv, LogBlock, ServerSelector, Buycraft, ViaVersion, WorldBorder, HolographicDisplays, Vault, WorldGuard, BungeePortals, Essentials, EchoPet, TrailGUI
```

It's a lobby server...

**Comment by L4BORG** [comment]
and PaperSpigot 1.8.8 (latest):

```
This server is running CraftBukkit version git-PaperSpigot-"5c510af" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

**Comment by Paulomart** [comment]
PaperSpigot dosent work

**Comment by MylesIsCool** [comment]
Try with normal spigot, if it works please say. Otherwise we'll continue investigating.
