### ISSUE TITLE
Failed to initialise chunks reflection on player join

### ISSUE THREAD

**Issue by TiTo-418** [MylesIsCool/ViaVersion#452]
### What version of ViaVersion are you using? Type /ver viaversion
http://prntscr.com/bkaeta

### What version of Spigot are you using? Type /ver
http://prntscr.com/bkaevk

### What plugins are you using? Type /plugins
http://prntscr.com/bkaf43

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[23:30:59 WARN]: Failed to initialise chunks reflection
java.lang.ClassNotFoundException: org.spigotmc.AntiXray
        at org.bukkit.plugin.java.PluginClassLoader.loadPluginClass(PluginClassLoader.java:162) ~[sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_73]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_73]
        at us.myles.ViaVersion.protocols.protocol1_9to1_8.storage.ClientChunks.<clinit>(ClientChunks.java:29) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.protocols.protocol1_9to1_8.Protocol1_9TO1_8.init(Protocol1_9TO1_8.java:128) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.add(ProtocolPipeline.java:58) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.protocols.base.BaseProtocol$3$1.handle(BaseProtocol.java:130) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:137) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:177) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:359) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at us.myles.ViaVersion.handlers.ViaDecodeHandler.decode(ViaDecodeHandler.java:57) [ViaVersion-0.9.5-SNAPSHOT.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [sportbukkit-1.8.7.jar:git-Bukkit-21840a7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
```

**Comment by TiTo-418** [comment]
Related commit: https://github.com/MylesIsCool/ViaVersion/commit/3ddc43bf7b64b79c3a27f14e0435e902100422d0

**Comment by Matsv** [comment]
Thanks for reporting, it's never tested it on SportBukkit.

**Comment by MylesIsCool** [comment]
It should still work even if that happens though i'll patch this issue so it doesn't happen.

**Comment by TiTo-418** [comment]
@MylesIsCool Thank you :3
