### ISSUE TITLE
java.lang.NullPointerException: handler

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#461]
### What version of ViaVersion are you using? Type /ver viaversion
```
>viaversion
[22:02:03 INFO]: ViaVersion 0.9.6
```

### What version of Spigot are you using? Type /ver
```
>ver
[22:01:25 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[22:01:25 INFO]: Checking version, please wait...
[22:01:25 INFO]: You are running the latest version
```

### What plugins are you using? Type /plugins
```
>pl
[22:00:29 INFO]: Plugins (22): AsyncWorldEditInjector, ServerManager, AsyncWorldEdit, HealthBar, OpenInv, PlugMan, SurvivalGames, ViaVersion, BuycraftX, Vault, Votifier, ProtocolLib, NoCheatPlus, WorldEdit, VoteListener, Essentials, NoCheatEnforcer, LogBlock, UserManager, HolographicDisplays, EssentialsSpawn, WorldGuard
```

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord with SkinsRestorer, ServerListPlus and NuVotifier

### How does this error happen? login? Using an item? 
Not sure, but it wasn't happening with exact the same setup and old version od ViaVersion (0.9.4).

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[21:56:14] [Server thread/WARN]: java.lang.NullPointerException: handler
[21:56:14] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.context(DefaultChannelPipeline.java:632)
[21:56:14] [Server thread/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.sendRawPacketFuture(UserConnection.java:97)
[21:56:14] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:307)
[21:56:14] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:321)
[21:56:14] [Server thread/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.listeners.ArmorListener.sendArmorUpdate(ArmorListener.java:53)
[21:56:14] [Server thread/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.listeners.ArmorListener.onWorldChange(ArmorListener.java:110)
[21:56:14] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
[21:56:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:56:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[21:56:14] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:644)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[21:56:14] [Server thread/WARN]: 	at me.wazup.survivalgames.PlayerData.restoreData(PlayerData.java:206)
[21:56:14] [Server thread/WARN]: 	at me.wazup.survivalgames.main.onCommand(main.java:370)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339)
[21:56:14] [Server thread/WARN]: 	at me.wazup.survivalgames.listener.onPlayerQuit(listener.java:726)
[21:56:14] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
[21:56:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:56:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[21:56:14] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[21:56:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:880)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[21:56:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[21:56:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Matsv** [comment]
Does it happen using the latest devbuild? http://ci.viaversion.com/job/ViaVersion/

**Comment by L4BORG** [comment]
Nope, it's ok now (with b#57) :)

**Comment by Matsv** [comment]
Thanks for testing :smile:

**Comment by MylesIsCool** [comment]
#BlameMyles

#MatsSavedUs
