### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Misat11** [MylesIsCool/ViaVersion#477]
Hi,
Whenever i am trying to connect from a different version than 1.9, I can not connect to the server.
On older viaversion 0.9.4 connection works without a problem.

Minecraft version: 1.9.4
ViaVersion: 0.9.8

In console:
[12:25:12] [Server thread/INFO]: Misat11 lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

In luncher:
[12:25:19] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(77) exceeds writerIndex(63): UnpooledHeapByteBuf(ridx: 1, widx: 63, cap: 63)
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.7.0_80]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.7.0_80]
	at h.a(SourceFile:46) [1.10.2.jar:?]
	at bcx.av(SourceFile:960) [1.10.2.jar:?]
	at bcx.a(SourceFile:396) [1.10.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.10.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(77) exceeds writerIndex(63): UnpooledHeapByteBuf(ridx: 1, widx: 63, cap: 63)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at eq.readBytes(SourceFile:759) ~[1.10.2.jar:?]
	at eq.e(SourceFile:333) ~[1.10.2.jar:?]
	at bll.a(SourceFile:1468) ~[1.10.2.jar:?]
	at gl.a(SourceFile:54) ~[1.10.2.jar:?]
	at gl.a(SourceFile:9) ~[1.10.2.jar:?]
	at fl$1.run(SourceFile:13) ~[1.10.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.7.0_80]
	at h.a(SourceFile:45) ~[1.10.2.jar:?]
	... 3 more

**Comment by MylesIsCool** [comment]
Please fill in the issue template seen at:
https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

Otherwise this info is not useful.

**Comment by Misat11** [comment]
Plugins:
[INFO] Plugins (50): Emoticons, CustomHelpPages, BarAPI, OnlyProxy, BungeePerms, NameHistory, SortingHopper_Precise, ViaVersion, Color4Signs, MountMe, dynmap, WorldEdit, Skript, AdvancedRespawn, SkinsModule, Essentials, PacketListenerApi, BukkitCompat, Modifyworld, MultiCommand, WeatherGod, LaggRemover, ProtocolLib, Multiverse-Core, broad-cast, EssentialsChat, iConomy, WarpSigns, Multiverse-Portals, pvpstats, SortingHopper, Vault, AuthMe, PerWorldInventory, HolographicDisplays, WorldGuard, mobmakemoney, Multiverse-NetherPortals, BungeeTabListPlus, AntiCheatReloaded, ChestLock, Jobs, Citizens, Residence, VillagerShop, CraftBook, AuthMeBridge, RecipeManager, ChestShop, SafeCreeper

I'm using BungeeCord from HexagonMC https://github.com/HexagonMC/BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:9a65016:84

**Comment by MylesIsCool** [comment]
Are you using any BungeePlugins?

**Comment by Misat11** [comment]
In bungeecord i'm using
BConfReloader, BungeeAuthMeBridge, BungeeBroadCaster, BungeeJoinMessages, BungeeMSG, BungeePerms, BungeePluginManager, BungeeRcon, BungeeTools-HubCommand, Globaltablist, ServerListPlus, SkinsRestorer, VersionConnector, Yamler

**Comment by MylesIsCool** [comment]
Try without SkinRestorer, and see if it still happens.

Otherwise try removing other plugins (test if the issue happens without bungee if you can).

**Comment by Misat11** [comment]
It works. :)
_(But I need this plugin, you do not know any compensation?)_
