### ISSUE TITLE
ProtocolLib PacketAdapters listening for PacketType.Play.Server.MAP_CHUNK causes exceptions for 1.9 clients

### ISSUE THREAD

**Issue by gigosaurus** [MylesIsCool/ViaVersion#48]
Upon joining (and the server attempting to send chunk data to the 1.9 client), you get one of these lovelies for each packet that would be sent:

    [14:11:14] [Netty Epoll Server IO #0/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
    java.io.IOException: Error while write(...): Broken pipe
	    at io.netty.channel.epoll.Native.writeAddress(Native Method) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.epoll.EpollSocketChannel.writeBytes(EpollSocketChannel.java:125) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.epoll.EpollSocketChannel.doWriteSingle(EpollSocketChannel.java:337) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:325) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:240) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:676) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1059) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:718) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[Spigot.jar:git-Spigot-db6de12-07c3001]
	    at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327) ~[?:?]
	    at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [Spigot.jar:git-Spigot-db6de12-07c3001]
	    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345) [ProtocolLib.jar:3.6.5-b222]
	    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [Spigot.jar:git-Spigot-db6de12-07c3001]
	    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [Spigot.jar:git-Spigot-db6de12-07c3001]
	    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

For example, creating a plugin and sticking the following line of code in the onEnable() will cause the above exception(s) to happen.
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, PacketType.Play.Server.MAP_CHUNK) {});
```

**Comment by Paulomart** [comment]
Is this with e8cc25baadcd02e91db139ce6cddb0f906b7eb2f?

**Comment by gigosaurus** [comment]
yes

**Comment by Paulomart** [comment]
Is this happing with all PacketTypes or just the chunk packet?

**Comment by gigosaurus** [comment]
PacketType.Play.Server.PLAYER_INFO works fine, so it isn't all of them. I haven't tried any others as those are the only ones I use. I'll test them all right now.

**Comment by Paulomart** [comment]
Yeah it could be the speacial handling for chunks

**Comment by gigosaurus** [comment]
MAP_CHUNK is the only one with this issue. All the other packets that should be working appear to be working.

**Comment by gigosaurus** [comment]
This still happens.
Could this be related to issue #38?
I'm thinking maybe the packets aren't being sent correctly, as when the bungee tries to decode the message and read the varint for the packet number, it throws an exception.

I also checked and all of the bytes for the chunk packets that get written in the transformer are correct and completely match what a spigot 1.9 server sends out, yet ours causes weird chunk issues.

**Comment by MylesIsCool** [comment]
Nah this isn't related, I believe the issue is the packet gets sent from in front of the ViaVersion transformer meaning it doesn't get transformed.

**Comment by Paulomart** [comment]
@MylesIsCool whats the state on this?

**Comment by MylesIsCool** [comment]
@Paulomart Not looked into it as it's most likely going take hours to solve.

**Comment by MylesIsCool** [comment]
I've just tried it and it seems to work fine? is this too good to be true? is life just a dream?

who knows,

@Paulomart @gigosaurus

**Comment by gigosaurus** [comment]
Noticed that I still had the code for this commented out, and when I uncommented I was getting issues again. With debug enabled I get the same stack trace as before.

I've tested with both the latest release and the latest dev build.
