### ISSUE TITLE
ViaVersion kicking certain people

### ISSUE THREAD

**Issue by DuckCraftPvP** [MylesIsCool/ViaVersion#510]
I am running 1.9.4 spigot with latest version of bungeecord.

People said this error was because of viaversion.

07:12:50 [INFO] [fernopenguin] <-> ServerConnector [hub] has connected
07:12:50 [SEVERE] [fernopenguin] <-> DownstreamBridge <-> [hub] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(200) exceeds writerIndex(21): UnpooledSlicedByteBuf(ridx: 3, widx: 21, cap: 21/21, unwrapped: PooledUnsafeDirectByteBuf(ridx: 81635, widx: 81916, cap: 131072))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(200) exceeds writerIndex(21): UnpooledSlicedByteBuf(ridx: 3, widx: 21, cap: 21/21, unwrapped: PooledUnsafeDirectByteBuf(ridx: 81635, widx: 81916, cap: 131072))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1389)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
    at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36)
    at net.md_5.bungee.protocol.packet.PlayerListHeaderFooter.read(PlayerListHeaderFooter.java:26)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 29 more
07:12:50 [INFO] [fernopenguin] <-> DownstreamBridge <-> [hub] has disconnected
07:12:50 [WARNING] [fernopenguin] -> UpstreamBridge - IOException: An established connection was aborted by the software in your host machine
07:12:50 [INFO] [fernopenguin] disconnected with: IOException : An established connection was aborted by the software in your host machine @ sun.nio.ch.SocketDispatcher:-2
07:12:50 [INFO] [fernopenguin] -> UpstreamBridge has disconnected

**Comment by Matsv** [comment]
Please follow the issue template, it's there for a reason.
(http://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md)

**Comment by Matsv** [comment]
Closing because you didn't respond.
Feel free to ask for a re-open when you followed the issue template (See above)
