### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#525]
### What is the output link of /viaversion dump?

1.11 dev latest.
**EDIT (by @Matsv):** http://hastebin.com/deqafukohi.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Nop.

### How does this error happen? login? Using an item? 

Don't know, maybe a firework.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://hastebin.com/erufupesuq.md

**Comment by Matsv** [comment]
Could you follow the issue template and use /ViaVersion dump?

**Comment by TheIntelloBox** [comment]
http://hastebin.com/deqafukohi.json

**Comment by Matsv** [comment]
And this does not happen using the latest official spigot build?

**Comment by TheIntelloBox** [comment]
The latest spigot build or the latest Via Version Stable Build ?

**Comment by Matsv** [comment]
Latest Spigot build, so this one: https://www.spigotmc.org/resources/viaversion.19254/download?version=111056

**Comment by TheIntelloBox** [comment]
I'm only using dev version because I want to allow my players to connect on 1.11, but before in 9.9 I hadn't got this error.

**Comment by Matsv** [comment]
I'm unable to reproduce it, could you debug it? Remove plugins until it no longer happens.

**Comment by TheIntelloBox** [comment]
I don't know, the error happens only sometimes.

**Comment by MylesIsCool** [comment]
This error is caused by having the wrong version of LibsDisguises:

It fails to make the right datawatcher for a firework disguise? 
```
java.lang.IllegalArgumentException
[20:56:33] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor327.newInstance(Unknown Source)
[20:56:33] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:56:33] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:56:33] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:16)
[20:56:33] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedWatchableObject.newHandle(WrappedWatchableObject.java:83)
[20:56:33] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedWatchableObject.<init>(WrappedWatchableObject.java:62)
[20:56:33] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.FlagWatcher.convert(FlagWatcher.java:112)
```

Then causes ViaVersion to implode as it's not too sure what the metadata is as it fails to make it.
