### ISSUE TITLE
An error occurred with entity meta data for PLAYER

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#58]
```
[23:29:51 INFO]: An error occurred with entity meta data for PLAYER
[23:29:51 INFO]: Old ID: 1 New ID: 1
[23:29:51 INFO]: Old Type: Short New Type: VarInt
[23:29:51 WARN]: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
[23:29:51 WARN]:        at us.myles.ViaVersion.metadata.MetadataRewriter.writeMetadata1_9(MetadataRewriter.java:76)
[23:29:51 WARN]:        at us.myles.ViaVersion.transformers.OutgoingTransformer.transformMetadata(OutgoingTransformer.java:498)
[23:29:51 WARN]:        at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:396)
[23:29:51 WARN]:        at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:63)
[23:29:51 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[23:29:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[23:29:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[23:29:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[23:29:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[23:29:51 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[23:29:51 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[23:29:51 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[23:29:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[23:29:51 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[23:29:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:29:51 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

and 1.9 clients are unable to connect... ViaVersion 0.4.4

**Comment by Paulomart** [comment]
@MylesIsCool I think the Type::byId function is not working. Maybe the enum has be reordered.

**Comment by Paulomart** [comment]
Not sure maybe its just a stupid type conversion in Java

**Comment by ChavitaHD** [comment]
I have this issue as well.

**Comment by MylesIsCool** [comment]
Plugin list?

**Comment by ChavitaHD** [comment]
http://prntscr.com/aahd3n

-----

Best Regards,
Salvador Castaneda

Owner of ParallaxMC
ParallaxMC <http://www.parallaxmc.com>

**Comment by zedwick** [comment]
I too have this issue, no plugins beside ViaVersion.

**Comment by zedwick** [comment]
Confirming this seems to be fixed, thanks!
