### ISSUE TITLE
Messages being sent in random order

### ISSUE THREAD

**Issue by BadassDevelop** [MylesIsCool/ViaVersion#610]
### What is the output link of /viaversion dump? 
[11:17:47] [Craft Scheduler Thread - 1616/WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_111]
	at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
https://gyazo.com/75c9b5de52b27cf3153ba8462d332aa9

### How does this error happen? login? Using an item? 
Long messages.
Example:
https://gyazo.com/794939957fd226128964e04a05155edf

That message is completely out of order.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error in console. Tried debug mode and all that, nothing fixed it.

This issue happened after I updated from a snapshot version on your dev builds to the latest one on Spigot; nothing else changed within a three-day span. It happens to all plugins that send messages 5 lines or more; EssentialsX, GAListener, my core plugin, mcMMO, etc.

**Comment by MylesIsCool** [comment]
Are you able to test this with just ViaVersion + EssentialsX?

**Comment by BadassDevelop** [comment]
I will upload them to a private server and test it.

**Comment by BadassDevelop** [comment]
Nevermind, I've found the issue. It's error with the latest ProtocolLib, ViaVersion, and LiteBans. I fixed it by stopping my server, then disabling LiteBans' usage of ProtocolLib, then restarting it.

**Comment by MylesIsCool** [comment]
So was the issue in ProtocolLib? or something like that, very odd

**Comment by BadassDevelop** [comment]
It was caused by ProcotolLib after I updated to 1.0.3

**Comment by MylesIsCool** [comment]
Interesting, thanks for the insight, does downgrading ProtocolLib fix it?

**Comment by BadassDevelop** [comment]
I am not sure, I'll check later.

**Comment by BadassDevelop** [comment]
There's another plugin causing this glitch. Item2Chat.

Now, I am left with three options:

- Disable or downgrade ViaVersion
- Disable or downgrade ProtocolLib
- Disable Item2Chat
