### ISSUE TITLE
Disconnect when using ProtocolLib

### ISSUE THREAD

**Issue by Paulomart** [MylesIsCool/ViaVersion#611]
### What is the output link of /viaversion dump? 
Cannot provide, sorry

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using latest BungeeCord (`1217`) and Spigot 1.8.8 (`git-Spigot-21fe707-e1ebe52`) with ProtocolLib
```
ver ViaVersion
[16:47:23 INFO]: ViaVersion version 1.0.3
[16:47:23 INFO]: Allow newer clients to join older server versions.
[16:47:23 INFO]: Authors: _MylesC and Matsv
ver ProtocolLib
[16:47:30 INFO]: ProtocolLib version 4.2.0
[16:47:30 INFO]: Provides read/write access to the Minecraft protocol.
[16:47:30 INFO]: Authors: dmulloy2 and comphenix
```

### Stacktrace BungeeCord:
```
16:51:49 [ERROR] [omart] <-> DownstreamBridge <-> [xx] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2515, widx: 2531, cap: 4096))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2515, widx: 2531, cap: 4096))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 29 more
```

### Spigot Log:
```
[16:51:49 INFO]: UUID of player omart is 6b7c43c2-b077-33b5-b7c1-f22f4632c515
[16:51:49 INFO]: omart[/XX.XX.XX.XX:XXXX] logged in with entity id 252 at ([world]-461.42994306614895, 64.0, 176.65816323764437)
[16:51:49 INFO]: CHUNK_BULK
[16:51:49 INFO]: omart lost connection: Disconnected
[16:51:49 INFO]: omart left the game.
```

### Steps to reproduce:
I made a plugin showing how the bug is triggered: https://github.com/Paulomart/viaversion-bug

**Comment by MylesIsCool** [comment]
Use async listeners when using protocollib with bulk chunks.


eg.
https://github.com/MylesIsCool/BKCommonLib/blob/3a80aa03aeb23e4928c63fdab0327e2e249ea255/src/main/java/com/bergerkiller/bukkit/common/internal/network/ProtocolLibPacketHandler.java#L263

**Comment by Paulomart** [comment]
Paulomart/viaversion-bug@c81f6837d6d2f4e8c8ae0bc55a7caf1b4dfce97c still not working for me.

**Comment by MylesIsCool** [comment]
Could you try this with the same format as above using the option async to ensure it's the same?

**Comment by Paulomart** [comment]
Yeah, with Paulomart/viaversion-bug@f0896870f840bb0714013471ba30224afc32497e it seems to work right, strange enough.
