### ISSUE TITLE
Is "Couldn't select trade" ViaVersion issue?

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#614]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/b558a0a00ed7b904e946a9c1d8411352

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, ServerListPlus

### How does this error happen? login? Using an item? 
Randomly on login...

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[05:57:23 ERROR]: Couldn't select trade
java.lang.IndexOutOfBoundsException
        at io.netty.buffer.EmptyByteBuf.readInt(EmptyByteBuf.java:470) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketDataSerializer.readInt(PacketDataSerializer.java:547) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2054) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[05:57:23 INFO]: Player lost connection: Invalid trade data!
```

I'm not even sure if this is ViaVersion issue?

**Comment by MylesIsCool** [comment]
You need to provide more info, I have no idea how to replicate this.

**Comment by L4BORG** [comment]
It seems to be random and it's also happening on our lobbies (no villagers or trading plugins there).

**Comment by MylesIsCool** [comment]
Could this be related to EchoPet?

**Comment by L4BORG** [comment]
Could be, we're running EchoPet there.

**Comment by Jannik8500** [comment]
I think you have the same problem as me: https://github.com/MylesIsCool/ViaVersion/issues/618

**Comment by MylesIsCool** [comment]
https://github.com/PaperMC/Paper/issues/388

Just ignore, hacked client, ban.
