### ISSUE TITLE
/viaversion dump not working.

### ISSUE THREAD

**Issue by PiggyPiglet** [MylesIsCool/ViaVersion#616]
I get this error when using /viaversion dump
`[05:21:07] [Server thread/INFO]: PiggyPiglet issued server command: /viaversion dump
[05:21:07] [Craft Scheduler Thread - 20/WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_91]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_91]
    at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-16c940b-0805f60]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-16c940b-0805f60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by MylesIsCool** [comment]
You can use the latest development build from ci.viaversion.com :)

We're just waiting for significant updates before rolling out.
