### ISSUE TITLE
Hackclient can spam errors in console

### ISSUE THREAD

**Issue by Jannik8500** [MylesIsCool/ViaVersion#618]
### Description
With the Hackclient "liquidbounce", players are able to spam errors in the console. 
Because the error message says I should report this error here, I'm doing this now. 

### My research
If I use ViaVersion on a 1.9.4 Server to support 1.9.4-1.11, I get the same error but not get kicked. 
Console Spam: http://pastebin.com/Pa9nrBQr

Looks like a spigot bug, this happens in minecraft 1.11.1 as well (without ViaVersion). But can't report this bug at spigot because the client does not wirk with spigot 1.11.2 which is the latest version.

### What is the output link of /viaversion dump? 
Could not create dump, sorry.

`[21:21:09 WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_101]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

### Are you using any additional software like BungeeCord? If so, what software and version? 
- BungeeCord: 1213
- NoCheatPlus
- my own (does sure not affect anything on this)

### How does this error happen? login? Using an item? 
Using "Console Spammer" with Hackclient "liquidbounce"

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message and error:
http://pastebin.com/MFHFD6fY

**Comment by MylesIsCool** [comment]
Any chance you can post below the error? (Seems to be missing some)

**Comment by MylesIsCool** [comment]
As per paper, this looks like hacked client:

https://github.com/PaperMC/Paper/issues/388


However there is also a viaversion error, which i'm unsure if it's solveable until I can see more info.

**Comment by Jannik8500** [comment]
@MylesIsCool There is nothing missing, the ViaVersion Error is empty after the ":".

Is there maybe anything to do to catch this error? It's really annoying for 1.8 Servers to have a console full of exceptions.

**Comment by MylesIsCool** [comment]
@Jannik8500 Well if you weren't using ViaVersion it would still happen, base case is to just ban the people who trigger it.

**Comment by Jannik8500** [comment]
@MylesIsCool Hmm, yes I'm already doing it but is there nothing to do on ViaVersion side to catch this exception? 

Anyway, I reported this bug to spigot (maybe there's something to do)

**Comment by MylesIsCool** [comment]
Without harming how verbose viaversion is with proper bugs, no
