### ISSUE TITLE
Anyone else getting this on startup?

### ISSUE THREAD

**Issue by MatthewSH** [MylesIsCool/ViaVersion#624]
Anyone getting this error on startup? I've been getting for a couple weeks now...
Truly weird.

```
[23:14:19] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:14:19] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:522)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	... 18 more
[23:14:19] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol$3$1.handle(BaseProtocol.java:165)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:232)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:54)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	... 20 more
[23:14:19] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:14:19] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:522)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	... 18 more
[23:14:19] [Netty Epoll Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$3 (Anonymous), Data: [Pair{Type|VarInt, 11}], Packet ID: 0}
Actual Error: 
[23:14:19] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(77) exceeds writerIndex(13): UnpooledHeapByteBuf(ridx: 3, widx: 13, cap: 13)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:19)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:8)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:146)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:232)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:54)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:522)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:14:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MylesIsCool** [comment]
This is most likely to a server list sending you bad data

**Comment by MatthewSH** [comment]
That's what I was thinking. Just making sure.
