### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by ErkePannekake** [MylesIsCool/ViaVersion#626]
### What is the output link of /viaversion dump? 
Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_111]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Citizens, Ultarcsometics, World Edit, some custom plugins i made myself, Voxel Sniper, And some more i dont want to list all my 29 plugins.
### How does this error happen? login? Using an item? 
Duplication glitch when you are in Creative 1.9 if you open inv and put any type of item in the secound hand it drops double amount.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No errors

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/217
