### ISSUE TITLE
ViaVersion 1.0.5-17w06a not work

### ISSUE THREAD

**Issue by x9nico** [MylesIsCool/ViaVersion#641]
Hi, I use this plugin on BungeeCord, and it is not work.
I've got this error:

15:59:04 [WARNING] Exception encountered when loading plugin: ViaVersion
java.lang.NullPointerException
	at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:54)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by x9nico** [comment]
It is the viaversion for 1.12

**Comment by MylesIsCool** [comment]
You've installed the wrong jar, use the multiplatform jar, https://ci.viaversion.com/job/ViaVersion-DEV/lastSuccessfulBuild/artifact/jar/target/ViaVersion-1.0.5-17w06a.jar

**Comment by x9nico** [comment]
It is not work.

**Comment by MylesIsCool** [comment]
Could you https://hastebin.com/ your full startup log?
