### ISSUE TITLE
Orebfuscator not working correctly

### ISSUE THREAD

**Issue by Inuun** [MylesIsCool/ViaVersion#644]
### What is the output link of /viaversion dump?
Not included

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
HexaCord (fork of BungeeCord) BungeeCord-Bootstrap:1.11-SNAPSHOT:5a1da1f:120 by md_5

### How does this error happen? login? Using an item? 
Exploring the world.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

### Issue
[Orebfuscator](https://github.com/MylesIsCool/Orebfuscator) not working correctly:
![obraz](https://cloud.githubusercontent.com/assets/25415267/24250850/8d8e5e50-0fd8-11e7-9b30-920e8351c5c3.png)

**Comment by MylesIsCool** [comment]
If you're not providing the output from ViaVersion dump how do you expect us to help?
Also have you ensured Orebfuscator has the correct settings?

**Comment by Inuun** [comment]
```[ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_101]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]```

I'm using default settings.

**Comment by MylesIsCool** [comment]
@Inuun You're definitely not on the latest ViaVersion can you ensure you're on latest ViaVersion and latest Orefuscator that I released.

**Comment by MylesIsCool** [comment]
See above.
