### ISSUE TITLE
ViaVersion with PacketLib (And a registered listener) cause error in BungeeCord

### ISSUE THREAD

**Issue by WolverinDEV** [MylesIsCool/ViaVersion#652]
Hello,
well sounds strange, but if im registering via ProtocollLib (ProtocolLib v4.2.1 (latest version))  a packet listener for the packet PacketPlayOutMapChunk and then trying to join over my BungeeCord (latest version) with the Minecraft versions 1.9-1.11 then the BungeeCord throws an error.

Via-Version dump: https://gist.github.com/anonymous/217d7cbcb0cef5bb7d08de5b749fb7a0
BungeeCord Error:
```
16:58:08 [SEVERE] [WolverinGER] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2486, widx: 2502, cap: 4096))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2486, widx: 2502, cap: 4096))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 27 more

```

Spigot-PacketListener:
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new com.comphenix.protocol.events.PacketListener() {
			@Override
			public void onPacketSending(PacketEvent arg0) {
				
			}
			
			@Override
			public void onPacketReceiving(PacketEvent arg0) {
				
			}
			
			@Override
			public ListeningWhitelist getSendingWhitelist() {
				return ListeningWhitelist.newBuilder().gamePhase(GamePhase.PLAYING).types(PacketType.Play.Server.MAP_CHUNK).build();
			}
			
			@Override
			public ListeningWhitelist getReceivingWhitelist() {
				return ListeningWhitelist.EMPTY_WHITELIST;
			}
			
			@Override
			public Plugin getPlugin() {
				return Main.getInstance();
			}
		});
```

**Comment by MylesIsCool** [comment]
Use async listeners for chunks, eg.
https://github.com/MylesIsCool/Orebfuscator/blob/47d25e5476b923e4434ca55fed20649345f7a23b/src/main/java/com/lishid/orebfuscator/hook/ProtocolLibHook.java#L37

or

https://github.com/MylesIsCool/BKCommonLib/blob/3a80aa03aeb23e4928c63fdab0327e2e249ea255/src/main/java/com/bergerkiller/bukkit/common/internal/network/ProtocolLibPacketHandler.java#L263

(Mark as async using options)

**Comment by WolverinDEV** [comment]
Well but this breaks my code and tooks a lots longer than the sync handling.
