### ISSUE TITLE
NullPointerException in 1.10 to 1.11 ItemRewriter when connecting with 1.12 over BungeeCord

### ISSUE THREAD

**Issue by Paulomart** [MylesIsCool/ViaVersion#663]
_Using viaversion dev_
### What is the output link of /viaversion dump? 
https://gist.github.com/905c09c3c80d259454efe28d55d09a34

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Tested and verifed without any plugins, using BungeeCord 1.12-pre2.

### How does this error happen? login? Using an item? 

On login the client is disconnected with `[Proxy] Lost connection to server.`

### Is there an error in the console? Use pastebin.com. Is there a kick message?

<details>
<summary>Expand for log</summary>
<pre>
[13:31:28] [Server thread/INFO]: Starting minecraft server version 1.8.8
[13:31:28] [Server thread/INFO]: Loading properties
[13:31:28] [Server thread/INFO]: Default game type: SURVIVAL
[13:31:28] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:31:28] [Server thread/INFO]: Debug logging is disabled
[13:31:28] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:31:28] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:31:28] [Server thread/INFO]: Generating keypair
[13:31:28] [Server thread/INFO]: Starting Minecraft server on *:25577
[13:31:28] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[13:31:28] [Server thread/INFO]: net.madgamble.core.injector.security.ASM is loaded by sun.misc.Launcher$AppClassLoader@42a57993
[13:31:28] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v1.0.5-1_12pre2
[13:31:28] [Server thread/INFO]: [ViaVersion] ViaVersion 1.0.5-1_12pre2 is now loaded, waiting for boot. (late-bind)
[13:31:28] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:31:28] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:31:28] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:31:28] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:31:28] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****

*SNIP*

[13:31:29] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v1.0.5-1_12pre2
[13:31:30] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:31:30] [Server thread/INFO]: Done (1,597s)! For help, type "help" or "?"
[13:31:30] [Server thread/INFO]: Using default channel type
[13:31:30] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x(47)
[13:31:30] [Server thread/WARN]: [ViaVersion] You are running a newer version than is released!
[13:31:38] [Thread-8/INFO]: UUID of player Paulomart is a60b9235-616d-34f2-96a5-633faddfd7da
[13:31:38] [Server thread/INFO]: Paulomart[/127.0.0.1:56318] logged in with entity id 112 at ([world]-432.0306719214542, 4.0, 531.6999999880791)
[13:31:38] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:31:38] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:31:38] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:31:38] [Netty Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.ItemRewriter.toClient(ItemRewriter.java:100)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.packets.InventoryPackets$2$1.handle(InventoryPackets.java:48)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:31:38] [Netty Server IO #1/WARN]: 	... 15 more
[13:31:38] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:31:38] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:31:38] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:31:38] [Netty Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.ItemRewriter.toClient(ItemRewriter.java:100)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.packets.InventoryPackets$1$1.handle(InventoryPackets.java:30)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:31:38] [Netty Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:31:38] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:31:38] [Netty Server IO #1/WARN]: 	... 15 more
[13:31:38] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:31:38] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:31:38] [Server thread/INFO]: Paulomart lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:31:38] [Server thread/INFO]: Paulomart left the game.
[13:31:49] [Craft Scheduler Thread - 0/INFO]: We've made a dump with useful information, report your issue and provide this url: https://gist.github.com/905c09c3c80d259454efe28d55d09a34
[13:33:44] [Thread-9/INFO]: UUID of player Paulomart is a60b9235-616d-34f2-96a5-633faddfd7da
[13:33:45] [Server thread/INFO]: Paulomart[/127.0.0.1:56447] logged in with entity id 123 at ([world]-432.0306719214542, 4.0, 531.6999999880791)
[13:33:45] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:33:45] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:33:45] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:33:45] [Netty Server IO #2/WARN]: Caused by: java.lang.NullPointerException
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.ItemRewriter.toClient(ItemRewriter.java:100)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.packets.InventoryPackets$2$1.handle(InventoryPackets.java:48)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:33:45] [Netty Server IO #2/WARN]: 	... 15 more
[13:33:45] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:33:45] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:33:45] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:33:45] [Netty Server IO #2/WARN]: Caused by: java.lang.NullPointerException
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.ItemRewriter.toClient(ItemRewriter.java:100)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.packets.InventoryPackets$1$1.handle(InventoryPackets.java:30)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:33:45] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:33:45] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:33:45] [Netty Server IO #2/WARN]: 	... 15 more
[13:33:45] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[13:33:45] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[13:33:45] [Server thread/INFO]: Paulomart lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[13:33:45] [Server thread/INFO]: Paulomart left the game.
</pre>
</details>

**Comment by Matsv** [comment]
Thanks <3
