### ISSUE TITLE
Error - bad - no ideea for title - Error

### ISSUE THREAD

**Issue by GabyUnalaq** [MylesIsCool/ViaVersion#685]
I'm using Spigot 1.12

Plugins (14): Brewery, WorldEdit, ChopTree3, Essentials, LoginSecurity, PacketListenerApi, PermissionsEx, RecipeManager, Lockette, MapManager, Multiverse-Core, SkinsRestorer, AnimatedFrames, Multiverse-Portals

Heeeelp
What ca I do to resolve this one?

[21:37:08 WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='entitiesById', types=[]}] in class class net.minecraft.server.v1_12_R1.WorldServer
[21:37:08 WARN]:        at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:158)
[21:37:08 WARN]:        at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:11)
[21:37:08 WARN]:        at org.inventivetalent.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60)
[21:37:08 WARN]:        at org.inventivetalent.reflection.resolver.FieldResolver.resolve(FieldResolver.java:57)
[21:37:08 WARN]:        at org.inventivetalent.mapmanager.MapManagerPlugin.getItemFrameById(MapManagerPlugin.java:165)
[21:37:08 WARN]:        at org.inventivetalent.mapmanager.event.MapInteractEvent.getItemFrame(MapInteractEvent.java:78)
[21:37:08 WARN]:        at org.inventivetalent.mapmanager.PacketListener$1.onReceive(PacketListener.java:77)
[21:37:08 WARN]:        at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:103)
[21:37:08 WARN]:        at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketReceive(PacketListenerAPI.java:105)
[21:37:08 WARN]:        at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketReceive(ChannelAbstract.java:89)
[21:37:08 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:151)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[21:37:08 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:154)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[21:37:08 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[21:37:08 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[21:37:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[21:37:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[21:37:08 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[21:37:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
[21:37:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
[21:37:08 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
[21:37:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[21:37:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[21:37:08 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by MylesIsCool** [comment]
You're not even using ViaVersion, the error is unrelated to this.
