### ISSUE TITLE
Getting Errors on Bungeecord

### ISSUE THREAD

**Issue by cengiz77** [MylesIsCool/ViaVersion#700]
Hi I'm using ViaVersion with latest version of bungeecord but it isn't work and occurs error. Here is the errors:

`java.lang.NullPointerException
    at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:54)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

`18:23:30 [WARNING] Error enabling plugin ViaVersion
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:254)
    at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
    at us.myles.ViaVersion.util.Config.loadConfig(Config.java:53)
    at us.myles.ViaVersion.util.Config.reloadConfig(Config.java:114)
    at us.myles.ViaVersion.util.Config.<init>(Config.java:33)
    at us.myles.ViaVersion.bungee.platform.BungeeConfigAPI.<init>(BungeeConfigAPI.java:15)
    at us.myles.ViaVersion.BungeePlugin.onLoad(BungeePlugin.java:39)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:223)
    ... 12 more`

**Comment by MylesIsCool** [comment]
This is down to your config being incorrectly formatted, delete it and allow ViaVersion to regenerate it.
