### ISSUE TITLE
Via Version IOException Error

### ISSUE THREAD

**Issue by raylin01** [MylesIsCool/ViaVersion#732]
### What is the output link of /viaversion dump? 
http://github.com/MylesIsCool/ViaVersion/issues{Type: Item Array, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$4 (Anonymo[18:45:56 INFO]: rlin01 left the game.}], Packet ID: 20}

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No. 
Plugins list: 
World Guard 6.1
World Edit 6.1
Warp Portals 5.6.5
Votifier 1.9
Via Version 1.0.4
Vault
Ultimate Plugin Updater
Sign Shop
Server Signs
Remote Controller 1.7.2
PvP1vs1 1.6.9
Ptweaks
Protocol Lib
Protection Lib
PartlyFancy 2.7.9.4
OpenInv
NoCheatPlus
Multiverse Portals 2.4
Multiverse Inventories 2.5
Multiverse Core 2.5
MOTDgd CommandAd
Minigame Lib 1.13.1
MG Splegg
MG Skywars
MCLib
MassiveCore
LuckyBlocks 1.6
LibDisguises
Jpanel
ImageOnMap 3.0
Hub
Factions
Essentials Spawn 2.x
Essentials Group Manager
Essentials Chat 2.x
Essentials 2.x
EnjinMinecraftPlugin
Editor Free v1.1
Dynmap 2.4
CoreProtect 2.12.0
BossBarAPI
BKCommonLib 
BarAPIReplacer
AutoTNT
AutoSaveWorld
AutoMessage
AntiSpam
AdminWatch 1.9
AdminEssentials

### How does this error happen? login? Using an item? 
Trying to connect to server

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The error: {Type: Item Array, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$4 (Anonymous), Data: [Pair{Type|Unsigned Byte, 0}], Packet ID: 20}

Kick message: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by Matsv** [comment]
Please give us your /ViaVersion dump output and the full exception. (You can get the full exception by changing 'debug' to 'true' in 'server.properties' and producing the error again).

Thanks

**Comment by raylin01** [comment]
[User Authenticator #1/INFO]: UUID of player rlin01 is 91239194-edf3-4861-89a0-9cb854c968b9
[19:26:18] [Server thread/INFO]: rlin01[/98.234.125.35:58455] logged in with entity id 1583 at ([skyisles]288.6423935297099, 4.495200877005911, -1124.721995243476)
[19:26:19] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Item Array, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$4 (Anonymous), Data: [Pair{Type|Unsigned Byte, 0}], Packet ID: 20}
Actual Error: 
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:26:19] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:26:19] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:26:19] [Netty Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Item Array, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$4 (Anonymous), Data: [Pair{Type|Unsigned Byte, 0}], Packet ID: 20}
Actual Error: 
[19:26:19] [Netty Server IO #2/WARN]: Caused by: java.lang.IllegalArgumentException: Cannot read NBT (got 3602749 bytes)
[19:26:19] [Netty Server IO #2/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.NBTType.read(NBTType.java:23)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.NBTType.read(NBTType.java:16)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ItemType.read(ItemType.java:22)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ItemType.read(ItemType.java:7)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ItemArrayType.read(ItemArrayType.java:18)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ItemArrayType.read(ItemArrayType.java:7)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:146)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[19:26:19] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[19:26:19] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[19:26:19] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:26:19] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:19] [Server thread/INFO]: rlin01 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Item Array, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$4 (Anonymous), Data: [Pair{Type|Unsigned Byte, 0}], Packet ID: 20}
Actual Error: 
[19:26:19] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:20] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:20] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:20] [Server thread/INFO]: rlin01 left the game.
[19:26:20] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:25] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:26] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:27] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[19:26:30] [Netty Server IO #2/WARN]: java.nio.channels.ClosedChannelException

That is what I got. Is there a location for the dump or is this it?

**Comment by MylesIsCool** [comment]
Just type the command "/ViaVersion dump" in console and it will provide a link you can paste here.

**Comment by raylin01** [comment]
Here you go:
[12:17:57 INFO]: We've made a dump with useful information, report your issue and provide this url: https://gist.github.com/f990a0f04f0e5a0f24ab51acc16eb6a7

**Comment by MylesIsCool** [comment]
Could you confirm if the bug happens without ProtocolLib for testing purposes?

**Comment by MylesIsCool** [comment]
See above, we ideally need to narrow down the cause.
