### ISSUE TITLE
Book signing is broken in some cases (1.9+ clients)

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#737]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/a173e6b7d63b630fe1919042d99bfad3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
How to replicate:
1. Get new book and quill
2. Put something in page 1 (whatever), put ONLY space (" ") in page 2
3. Sign the book

Furthermore, trying to handle this in PlayerEditBookEvent will not work as bookMeta.getPages() is also broken if you're trying to loop it.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[13:44:42 ERROR]: Couldn't sign book
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.stripEvents(CraftEventFactory.java:884) ~[patched.jar:git-TacoSpigot-"c2835df"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEditBookEvent(CraftEventFactory.java:872) ~[patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2032) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"c2835df"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c2835df"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c2835df"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:44:42 INFO]: Player lost connection: Invalid book data!
```

**Comment by MylesIsCool** [comment]
I'm able to replicate this, not sure what the solution is, maybe strip empty pages.

As a side note for anyone else looking at this issue the NBT it sends is "Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|String, MC|BSign}, Pair{Type|Item, Item(id=387, amount=1, data=0, tag=CompoundTag { {pages=ListTag(pages) { [StringTag { dfgdfgsdg }, StringTag {   }] }, author=StringTag(author) { _MylesC }, title=StringTag(title) { dg }} })}]"
