### ISSUE TITLE
NPE error when using a protocollib packet listener for MAP_CHUNK

### ISSUE THREAD

**Issue by MedicOP** [MylesIsCool/ViaVersion#748]
ViaVersion 1.2.0
Spigot 1.8.9

Logging in from a client that is 1.9 or higher will not work. Logs show the error
```java
[11:43:19 WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk@394dae47 to MedicOP
java.lang.NullPointerException: player cannot be null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.getPlayerConnection(ChannelInjector.java:727) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:679) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$600(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$6.run(ChannelInjector.java:504) [ProtocolLib.jar:4.3.0]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

To reproduce the problem, just make a plugin with a ProtocolLib packet listener for the MAP_CHUNK packet.

```java
ProtocolManager protocolManager = ProtocolLibrary.getProtocolManager();
        protocolManager.addPacketListener(new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.MAP_CHUNK)
```

**Comment by MylesIsCool** [comment]
Use async listeners for bulk chunk packets. See https://github.com/MylesIsCool/BKCommonLib for an example.

**Comment by MedicOP** [comment]
The single chunk packets don't need sync listener?

**Comment by MylesIsCool** [comment]
The only advice I can give is maybe to look at this:

https://www.spigotmc.org/threads/content-management-interface-mysql-sqlite-support-paid.48111/page-28#post-1400012

Could you be possibly doing something simialr?

**Comment by MedicOP** [comment]
I have @Override annotation so.. I don't see how that would fix anything anyway since the Java compiler would add it anyway

**Comment by MedicOP** [comment]
In any case making the listeners async fixed the issue

**Comment by IBROI** [comment]
Faced the same problem, prompt the decision, tried everything, but nothing works (

**Comment by MedicOP** [comment]
@IBROI make the listener async and it works

**Comment by IBROI** [comment]
http://prntscr.com/lyz9o6

I did it, but it does not solve my problems

**Comment by MedicOP** [comment]
```ProtocolManager protocolManager = ProtocolLibrary.getProtocolManager();
protocolManager.addPacketListener(new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.MAP_CHUNK) {

    private final ListeningWhitelist whitelist = ListeningWhitelist.newBuilder().types(PacketType.Play.Server.MAP_CHUNK).options(Arrays.asList(ListenerOptions.ASYNC)).build();

    @Override
    public void onPacketSending(PacketEvent event) {
        // TODO
    }

    @Override
    public ListeningWhitelist getSendingWhitelist() {
        return whitelist;
    }

});```

**Comment by MedicOP** [comment]
You're doing syncStart() which starts it on the main thread.. You have to use start()

**Comment by IBROI** [comment]
thank you very much
