### ISSUE TITLE
1.8.8 doesn't work on most of my servers

### ISSUE THREAD

**Issue by UberMC** [MylesIsCool/ViaVersion#750]
When 1.12.2 users connect to 1.8.8 w/ViaVersion they disconnect. (Disconnected)

Server running is 1.8.8, have issue on JAVA 7 and 8.
Tried removing all plugins, possibly map related I really don't know.

This error happens on some of my 1.8.8 servers. it should be noted that the maps generated could be old like 1.7 or before. Again I'm not sure if this is relevant.

### What is the output link of /viaversion dump? 
https://gist.github.com/194f8b886b4a0524c4713622ad0e74fe

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
3 Seconds after login (See map then disconnect)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
`14:36:33 [SEVERE] [ubermcnet] -> UpstreamBridge - encountered exception
https://hastebin.com/oxozulewew.lua
java.lang.RuntimeException: VarInt too big
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:114)
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
        at net.md_5.bungee.entitymap.EntityMap.rewriteVarInt(EntityMap.java:100)
        at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:219)
        at net.md_5.bungee.entitymap.EntityMap.rewriteServerbound(EntityMap.java:76)
        at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteServerbound(EntityMap_1_12_1.java:161)
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:111)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
14:36:33 [INFO] [ubermcnet] disconnected with: §fRuntimeException : VarInt too big @ net.md_5.bungee.protocol.DefinedPacket:114
14:36:33 [INFO] [ubermcnet] -> UpstreamBridge has disconnected`

**Comment by kjl13** [comment]
That is a bungeecord error. Not from viaversions.

**Comment by MylesIsCool** [comment]
This is a bug in BungeeCord, https://github.com/SpigotMC/BungeeCord/issues/2258


If you're risky I compiled a build with the fix earlier - http://myles.us/ViaVersion/test/BungeeCord-Fixed.jar

**Comment by kjl13** [comment]
if you're risky Myles compiled a build with the fix earlier - http://myles.us/ViaVersion/test/BungeeCord-Fixed.jar

**Comment by UberMC** [comment]
Wow amazing response time! Incoming donation :)
