### ISSUE TITLE
ViaVersion not loading

### ISSUE THREAD

**Issue by lukeeexd** [MylesIsCool/ViaVersion#769]
Hi, ViaVersion currently stopped loading, getting this error: 

[18:51:51] [Server thread/ERROR]: Could not load 'plugins/ViaVersion-1.3.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: while parsing a block mapping
 in 'reader', line 13, column 1:
    checkforupdates: true
    ^
expected <block end>, but found FlowEntry
 in 'reader', line 18, column 23:
    block-protocols: [107],[108],[109],[110]
                          ^

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [PaperSpigot-latest.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [PaperSpigot-latest.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [PaperSpigot-latest.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-latest.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 13, column 1:
    checkforupdates: true
    ^
expected <block end>, but found FlowEntry
 in 'reader', line 18, column 23:
    block-protocols: [107],[108],[109],[110]
                          ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:436) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at us.myles.ViaVersion.util.Config.loadConfig(Config.java:61) ~[?:?]
	at us.myles.ViaVersion.util.Config.reloadConfig(Config.java:122) ~[?:?]
	at us.myles.ViaVersion.bukkit.platform.BukkitConfigAPI.<init>(BukkitConfigAPI.java:20) ~[?:?]
	at us.myles.ViaVersion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:54) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[PaperSpigot-latest.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[PaperSpigot-latest.jar:git-Paper-1220]
	... 6 more

**Comment by MylesIsCool** [comment]
You're putting invalid YAML. Lists are in the form [1,2,3] not [1],[2] etc.

**Comment by lukeeexd** [comment]
Oh, thank you. It worked the way i had it before so not sure. Fixed it anyway. thank you for the speedy response
