### ISSUE TITLE
My Server problem

### ISSUE THREAD

**Issue by MatinDark** [MylesIsCool/ViaVersion#775]
Hello i use latest  verison of bungeecord ( already installed viaversion on bungeecord server ) and i have three server on 1.12.1 paper spigot and use latest protocolib viaversion and viabackward and 8 or 9 of my server run on spigot 1.9.4 with latest  version of protocolib and viaversion but when some players come with 1.12.1 .12.1 or some other version (just 1.9.4 it's ok )some times kick them kick them and say [proxy] lost connection or java exception error ..... what  should i do some times i see this error on console :
```
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(7787) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 3, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 16, cap: 192))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.
```
viaversion dump  bungeecord : https://gist.github.com/ee3792b4a3f1015215eb26f8a723b59d

**Comment by MylesIsCool** [comment]
This will be down to a plugin sending bad data, based on your plugins I'd suggest trying without SkinRestorer.

Also ensure you only run ViaVersion on bungee or spigot

**Comment by MatinDark** [comment]
My server is cracked one and ita not online mod and my players need skin
And of i install viaversion on bungeecord what should i do about viabackward for my 1.12.1 servers ?

**Comment by MylesIsCool** [comment]
I can't help you if you're using a plugin that sends bad packet data, in the current configuration you either use one plugin or the other on Bungee. Several people have Skin Restorer working. (Most likely latest versions, and ViaVersion/ViaBackwards only on Spigot servers)

ViaVersion can be used on Bungee OR Spigot, which you install ViaBackwards where ViaVersion is installed.

**Comment by MatinDark** [comment]
i delete viaversion and viabackward on standalone servers after that i install viabackward and viaversion on my bungeecord all servers fine and can join with 1.9.x - 1.12.x and problems solved when i think every thing is okey i saw new problem players can't join on skyblock server with version between 1.9.x .1.11.x they only can join with 1.12.1 because skyblock run on paper spigot 1.12.1
dump : https://gist.github.com/35800015f40e21978da1e6b6a738afaf

and onther thing how can turn of viabackward warning on bungeecord it's little spammy
`22:23:42 [WARNING] [ViaBackwards] Metadata for entity id: 183580 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=8)])
22:23:43 [INFO] [/151.240.232.226:21611] <-> InitialHandler has connected
22:23:43 [WARNING] [ViaBackwards] Metadata for entity id: 183580 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:23:43 [WARNING] [ViaBackwards] Metadata for entity id: 181706 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:23:44 [WARNING] [ViaBackwards] Metadata for entity id: 183580 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=7, metaType=Float, value=20.0)])`

**Comment by MatinDark** [comment]
i delete viaversion on standalone servers and install viabackward on bungeecord my 1.9.4 servers fine and can connect with 1.9.x-1.12.x without porblems but 1.12.1 and 1.12.2 paper spigot servers have still problem and viabackward spam this warning in my console
`metaDataList=[Metadata(id=0, metaType=Byte, value=8)])
22:46:20 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:46:20 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=8, metaType=VarInt, value=7222420), Metadata(id=9, metaType=Boolean, value=true)])
22:46:20 [WARNING] [ViaBackwards] Metadata for entity id: 202922 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=7, metaType=Float, value=19.0)])
22:46:20 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=8)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=7, metaType=Float, value=19.0)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 192657 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=12, metaType=VarInt, value=6279)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=8)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 187771 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 202935 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])
22:46:21 [WARNING] [ViaBackwards] Metadata for entity id: 181425 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0)])`

and some erros on bungee cord only for 1.12.1 and 1.12.2 servers
`22:48:56 [SEVERE] [morteza4444] <-> DownstreamBridge <-> [SkyBlock] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(5073) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 3, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 14, cap: 144))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(5073) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 3, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 14, cap: 144))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1388)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:870)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:878)
    at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36)
    at de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket.read(ResourcePackSendPacket.java:86)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 25 more`

**Comment by MylesIsCool** [comment]
The errors provided are to-do with plugins sending bad entity data, you may be able to suppress these via suppress-metadata-errors in the main ViaVersion config.yml
