### ISSUE TITLE
Broken Pipe Bungeecord Hub -> Server Issue

### ISSUE THREAD

**Issue by Reversiya** [MylesIsCool/ViaVersion#817]
### What is the output link of /viaversion dump? 
> [15:57:16 INFO]: Failed to dump, please check the console for more information
> [15:57:16 WARN]: [ViaVersion] Could not paste ViaVersion dump to Gist
java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/gists
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_161]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_161]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_161]
at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:87) [ViaVersion-1.3.0.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [paper.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [paper.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Hexacord - Hexagon Bungeecord latest version
BungeeVPNBlocker2.0 - Bungee Plugin
OnlyProxyJoin - Server Plugins

### How does this error happen? login? Using an item? 
Login Error Broken Pipe - 1.7.10
Login Error Broken Pipe - 1.8
Can Not Test - 1.9 and Above

Hub is running a modified spigot 1.7-1.8 build, game is running 1.8.8 + via version and rewind maybe this is causing some issues
Connecting with 1.12 or 1.7 while server was disonnected from bungee caused some issues

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Bungeecord Console:
https://pastebin.com/DVtaN4KL

###### VIAVERSION DEBUG ##########
Lots of Console Spam:
https://pastebin.com/wxC91k2P

**Comment by MylesIsCool** [comment]
This issue is down to either:

Bad spigot plugin
Bad bungee plugin

or something in ViaRewind, the only way to work this out is by trial and error, unfortunately.

**Comment by Logics4** [comment]
@MylesIsCool isn't the /viaversion dump error related to the fact that Github doesn't allow us to do anonymous gists anymore?

**Comment by Reversiya** [comment]
@MylesIsCool 
Entire Hub Server - Replaced - Did not solve
Bungeecord Replaced - Did not solve
Game Server - jar, paper.yml, spigot.yml, properties, bukkit.yml Replaced - Did not solve
Interesting errors of Stop server, delete session.lock on World to resolve issues.
Is there something that corrupts session.lock in minecraft worlds using viaversion of viarewind?

I believe that just joining on 1.7 or 1.12 while the server was offline permanently corrupted something on the server.
