### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by KohGeek** [MylesIsCool/ViaVersion#825]
I'm aware this might not be a ViaVersion issue, but ViaVersion 1.3.0 seems to bug TrollCommands++ when installed.

I'm running on Windows 10, and unknown Linux Host, running on Java 8 1.8.171, running on Spigot-1.12.2.

[TrollCommands++ 6.28.53](https://www.spigotmc.org/resources/trollcommands-troll-your-frenemies.24237/)

Links to related issues on respective plugins:
[LandLord Issues](https://github.com/SpatiumPrinceps/LandLord/issues/75)
[TrollCommands++ Issues](https://github.com/egg82/TrollCommandsPlusPlus/issues/6)

Crash log of testing:
```
[00:00:38 ERROR]: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder; initializing TrollCommandsPlusPlus v6.28.53 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
        at me.egg82.tcpp.lib.ninja.egg82.utils.ReflectUtil.getClasses(ReflectUtil.java:203) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.utils.VersionUtil.getBestMatch(VersionUtil.java:49) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.reflect(BasePlugin.java:181) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.reflect(BasePlugin.java:178) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.onLoad(BasePlugin.java:90) ~[?:?]
        at me.egg82.tcpp.TrollCommandsPlusPlus.onLoad(TrollCommandsPlusPlus.java:117) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:310) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

Continued crash log, further down the one above:
```
[00:01:08 ERROR]: Error occurred while enabling TrollCommandsPlusPlus v6.28.53 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
        at me.egg82.tcpp.lib.ninja.egg82.utils.ReflectUtil.getClasses(ReflectUtil.java:203) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.handlers.EventListener.<init>(EventListener.java:38) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_171]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.initializeService(ServiceLocator.java:136) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.provideService(ServiceLocator.java:73) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.onEnable(BasePlugin.java:117) ~[?:?]
        at me.egg82.tcpp.TrollCommandsPlusPlus.onEnable(TrollCommandsPlusPlus.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by MylesIsCool** [comment]
We're not doing anything on our end that would cause this issue. If it were shaded library we related we shade into our own namespace.

I suspect the issue you're having is between the other 2 plugins. As per your other issue "ViaVersion only installed: TC++ loads normally.", the only time is the issue occurs is when you're trying with the other plugins.
