### ISSUE TITLE
Enderman metadata error

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#865]
Paper dev 1500 (Spigot 1.12.2)
Waterfall dev 192 (Upstream with BungeeCord dev 1333)

ViaVersion-dev build 146
ViaBackwards-dev build 59
ViaRewind v1.3.10

All Via plugins are installed on both BungeeCord & Spigot server.

https://paste.ubuntu.com/p/3dq8YMx8yG/

```
[12:58:36] [Netty Worker IO Thread #15/INFO]: Could not find flowerpot content  for CompoundTag { {Item=StringTag(Item) {  }, x=IntTag(x) { -32 }, y=IntTag(y) { 56 }, z=IntTag(z) { -42 }, Data=IntTag(Data) { 0 }, id=StringTag(id) { minecraft:flower_pot }} }
```
```
[12:58:21] [Netty Worker IO Thread #6/ERROR] [ViaVersion]: An error occurred with entity meta data for ENDERMAN OldID: 17
[12:58:21] [Netty Worker IO Thread #6/ERROR] [ViaVersion]: Value: 0
[12:58:21] [Netty Worker IO Thread #6/ERROR] [ViaVersion]: Old ID: 17 New ID: 11
[12:58:21] [Netty Worker IO Thread #6/ERROR] [ViaVersion]: Old Type: Byte New Type: BlockID
[12:58:21] [Netty Worker IO Thread #6/ERROR]: java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Byte
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.metadata.MetadataRewriter.transform(MetadataRewriter.java:69)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.SpawnPackets$5$3.handle(SpawnPackets.java:218)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:151)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:424)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:61)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:18)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:185)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:123)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:58:21] [Netty Worker IO Thread #6/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
```

```
	Line 2397: [13:08:08] [Netty Worker IO Thread #15/INFO]: Missing block completely 67280
	Line 3009: [13:26:40] [Netty Worker IO Thread #4/INFO]: Missing block completely 66608
	Line 3075: [13:32:39] [Netty Worker IO Thread #7/INFO]: Missing block completely 67552
	Line 3120: [13:35:24] [Netty Worker IO Thread #13/INFO]: Missing block completely 133760
	Line 3144: [13:37:45] [Netty Worker IO Thread #13/INFO]: Missing block completely 133760
	Line 3145: [13:37:50] [Netty Worker IO Thread #13/INFO]: Missing block completely 133760
	Line 3149: [13:39:11] [Netty Worker IO Thread #13/INFO]: Missing block completely 133760
	Line 3156: [13:39:36] [Netty Worker IO Thread #13/INFO]: Missing block completely -523584
```

**Comment by MylesIsCool** [comment]
The majority of the issues in the issue should be fixed in the latest build.

Otherwise can you provide the output of /viaversion dump? (Do you use custom enderman plugin or anything like that?)

**Comment by MylesIsCool** [comment]
Provide info for the issue above & hopefully we'll reopen + fix :)

**Comment by mibby** [comment]
Sorry, didn't see you had replied.

Fortunately the error no longer seems to be occurring so I am going to assume it has been fixed.
