### ISSUE TITLE
Netty Epoll Server IO

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#89]
### What version of ViaVersion are you using? Type /ver viaversion
_ViaVersion version 0.4.6_

### What version of Spigot are you using? Type /ver
_This server is running CraftBukkit version git-PaperSpigot-"5c510af" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)_

### What plugins are you using? /plugins
_AsyncWorldEditInjector, ServerManager, NoCheatPlus, AutoSaveWorld, WorldEdit, AsyncWorldEdit, OpenInv, LogBlock, ServerSelector, Buycraft, ViaVersion, WorldBorder, HolographicDisplays, Vault, WorldGuard, BungeePortals, Essentials, EchoPet, TrailGUI_

### How does this error happen? login? using an item? 
_Not sure, yes._

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[15:48:00] [Netty Epoll Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while write(...): Broken pipe
	at io.netty.channel.epoll.Native.writeAddress(Native Method) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytes(EpollSocketChannel.java:125) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteSingle(EpollSocketChannel.java:337) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:325) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:240) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:676) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1059) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:718) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-lobby.jar:git-PaperSpigot-"5c510af"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by Paulomart** [comment]
Paper spigot is currently not supported
