### ISSUE TITLE
Client gets disconnected when custom entity is spawned

### ISSUE THREAD

**Issue by apollosoftware** [MylesIsCool/ViaVersion#925]
`[18:07:36 WARN]: Caused by: java.lang.NullPointerException
[18:07:36 WARN]:        at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2.getNewSoundID(Protocol1_13To1_12_2.java:801)
[18:07:36 WARN]:        at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2.access$000(Protocol1_13To1_12_2.java:38)
[18:07:36 WARN]:        at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$13$1.handle(Protocol1_13To1_12_2.java:435)
`
This is the error that prints whenever an entity is spawned on the latest version.
Dump: https://dump.viaversion.com/028c92e8b5a7bb131e5e0cb57d12f1c7a7bc2b2a073a73bf8e41a8d3b6ddc6df
Client: v1.13
Server (Modded Spigot Jar): v1.12

**Comment by MylesIsCool** [comment]
This should be fixed in the latest dev build.
