### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Saynni** [MylesIsCool/ViaVersion#966]
[21:43:08] [Netty Server IO #1/WARN]: java.lang.NullPointerException
[21:43:08] [Netty Server IO #1/WARN]: 	at de.gerrygames.viarewind.utils.PacketUtil$1.run(PacketUtil.java:41)
[21:43:08] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[21:43:08] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
[21:43:08] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[21:43:08] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[21:43:08] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:43:08] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Logics4** [comment]
This has to be with ViaRewind, not with ViaVersion. Please report this at ViaRewind's github issue tracker.

**Comment by Saynni** [comment]
Okay thanks, sorry ^^
