### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by RandalZ15** [MylesIsCool/ViaVersion#998]
[23:40:11] [User Authenticator #8/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@154e6725[id=233f4cac-5261-3675-8b3a-bba5032dd6da,name=mskfrioe,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) ~[patched_1.12.2.jar:git-Paper-1550]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[patched_1.12.2.jar:git-Paper-1550]
	at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:301) ~[patched_1.12.2.jar:git-Paper-1550]
	at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:206) ~[patched_1.12.2.jar:git-Paper-1550]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Logics4** [comment]
We need more information, otherwise it's not related to ViaVersion as that log doesn't say anything that could be linked to the plugin.

That error basically says your server sent too many requests to Mojang's servers and you were rate-limited. The max number of requests is 600 per 10 minutes.  That is usually caused by other plugins that need to request information to Mojang through their API.
Can you run `/viaversion dump` and send it here, please?

**Comment by RandalZ15** [comment]
https://dump.viaversion.com/0c3ab9ebb0cd0c92426cfd1e27db0f17a857b0fb22b95a93b05465d9

**Comment by RandalZ15** [comment]
The problem started immediately after installing the Via Version

**Comment by MylesIsCool** [comment]
This error isn't related to viaversion and if it still happens will also happen without.

It is as the error states, something is causing you to send too many requests to Mojang.
